
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int DELIMITER = 48;
  public static final int REAL_TYPE = 36;
  public static final int LBRACKET = 41;
  public static final int CHAR = 37;
  public static final int COMMENT = 51;
  public static final int PYCCS = 16;
  public static final int SERIAL = 34;
  public static final int INTEGER = 28;
  public static final int PC = 18;
  public static final int PA = 17;
  public static final int DATE = 33;
  public static final int VIRGULA = 53;
  public static final int DELETE = 15;
  public static final int WHERE = 13;
  public static final int NUMERIC = 39;
  public static final int NOT = 6;
  public static final int IGUAL = 25;
  public static final int COMMA = 44;
  public static final int REFERENCES = 10;
  public static final int VARCHAR = 30;
  public static final int NUM = 55;
  public static final int SELECT = 11;
  public static final int IF = 5;
  public static final int ID = 2;
  public static final int BOOLEAN = 38;
  public static final int EOF = 0;
  public static final int KEYWORD = 49;
  public static final int RBRACKET = 42;
  public static final int TABLE = 4;
  public static final int error = 1;
  public static final int DISTINCT = 23;
  public static final int COMA = 19;
  public static final int VALUES = 22;
  public static final int NULL = 45;
  public static final int TIMESTAMP = 32;
  public static final int EXISTS = 7;
  public static final int NUMBER = 50;
  public static final int INTEGER_TYPE = 35;
  public static final int ATRIBUTO = 54;
  public static final int ERROR = 52;
  public static final int FROM = 12;
  public static final int REAL = 29;
  public static final int INTO = 21;
  public static final int MEN = 26;
  public static final int INSERT = 20;
  public static final int CREATE = 3;
  public static final int APOSTROPHE = 43;
  public static final int SMALLINT = 40;
  public static final int STRING = 57;
  public static final int KEY = 9;
  public static final int OPERATOR = 47;
  public static final int ALL = 24;
  public static final int TEXT = 31;
  public static final int TODOS = 46;
  public static final int COUNT = 14;
  public static final int MAY = 27;
  public static final int PRIMARY = 8;
  public static final int IDENTIFIER = 56;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CREATE",
  "TABLE",
  "IF",
  "NOT",
  "EXISTS",
  "PRIMARY",
  "KEY",
  "REFERENCES",
  "SELECT",
  "FROM",
  "WHERE",
  "COUNT",
  "DELETE",
  "PYCCS",
  "PA",
  "PC",
  "COMA",
  "INSERT",
  "INTO",
  "VALUES",
  "DISTINCT",
  "ALL",
  "IGUAL",
  "MEN",
  "MAY",
  "INTEGER",
  "REAL",
  "VARCHAR",
  "TEXT",
  "TIMESTAMP",
  "DATE",
  "SERIAL",
  "INTEGER_TYPE",
  "REAL_TYPE",
  "CHAR",
  "BOOLEAN",
  "NUMERIC",
  "SMALLINT",
  "LBRACKET",
  "RBRACKET",
  "APOSTROPHE",
  "COMMA",
  "NULL",
  "TODOS",
  "OPERATOR",
  "DELIMITER",
  "KEYWORD",
  "NUMBER",
  "COMMENT",
  "ERROR",
  "VIRGULA",
  "ATRIBUTO",
  "NUM",
  "IDENTIFIER",
  "STRING"
  };
}

