/*
 * generated by Xtext 2.23.0
 */
package mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.Model");
		private final Assignment cElementAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementElementParserRuleCall_0 = (RuleCall)cElementAssignment.eContents().get(0);
		
		//Model:
		//	Element+=Element*;
		@Override public ParserRule getRule() { return rule; }
		
		//Element+=Element*
		public Assignment getElementAssignment() { return cElementAssignment; }
		
		//Element
		public RuleCall getElementElementParserRuleCall_0() { return cElementElementParserRuleCall_0; }
	}
	public class ElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.Element");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCREATEParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cALTERParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cINSERTParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSELECTParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDELETEParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cDROPTABLEParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cTRUNCATEParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cUPDATEParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cSELECTFUNCTParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cDATABASEParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		private final RuleCall cVariableDeclarationParserRuleCall_10 = (RuleCall)cAlternatives.eContents().get(10);
		
		//Element:
		//	CREATE | ALTER | INSERT | SELECT | DELETE | DROPTABLE | TRUNCATE | UPDATE | SELECTFUNCT | DATABASE |
		//	VariableDeclaration;
		@Override public ParserRule getRule() { return rule; }
		
		//CREATE | ALTER | INSERT | SELECT | DELETE | DROPTABLE | TRUNCATE | UPDATE | SELECTFUNCT | DATABASE | VariableDeclaration
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CREATE
		public RuleCall getCREATEParserRuleCall_0() { return cCREATEParserRuleCall_0; }
		
		//ALTER
		public RuleCall getALTERParserRuleCall_1() { return cALTERParserRuleCall_1; }
		
		//INSERT
		public RuleCall getINSERTParserRuleCall_2() { return cINSERTParserRuleCall_2; }
		
		//SELECT
		public RuleCall getSELECTParserRuleCall_3() { return cSELECTParserRuleCall_3; }
		
		//DELETE
		public RuleCall getDELETEParserRuleCall_4() { return cDELETEParserRuleCall_4; }
		
		//DROPTABLE
		public RuleCall getDROPTABLEParserRuleCall_5() { return cDROPTABLEParserRuleCall_5; }
		
		//TRUNCATE
		public RuleCall getTRUNCATEParserRuleCall_6() { return cTRUNCATEParserRuleCall_6; }
		
		//UPDATE
		public RuleCall getUPDATEParserRuleCall_7() { return cUPDATEParserRuleCall_7; }
		
		//SELECTFUNCT
		public RuleCall getSELECTFUNCTParserRuleCall_8() { return cSELECTFUNCTParserRuleCall_8; }
		
		//DATABASE
		public RuleCall getDATABASEParserRuleCall_9() { return cDATABASEParserRuleCall_9; }
		
		//VariableDeclaration
		public RuleCall getVariableDeclarationParserRuleCall_10() { return cVariableDeclarationParserRuleCall_10; }
	}
	public class REALElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.REAL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//REAL ecore::EFloat hidden():
		//	INT? "." INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT? "." INT
		public Group getGroup() { return cGroup; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//"."
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	public class SELECTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.SELECT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSELECTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cAsteriskKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Assignment cColumnAssignment_1_1_0 = (Assignment)cGroup_1_1.eContents().get(0);
		private final CrossReference cColumnCDCrossReference_1_1_0_0 = (CrossReference)cColumnAssignment_1_1_0.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_1_1_0_0_1 = (RuleCall)cColumnCDCrossReference_1_1_0_0.eContents().get(1);
		private final Group cGroup_1_1_1 = (Group)cGroup_1_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_1_0 = (Keyword)cGroup_1_1_1.eContents().get(0);
		private final Assignment cColumnAssignment_1_1_1_1 = (Assignment)cGroup_1_1_1.eContents().get(1);
		private final CrossReference cColumnCDCrossReference_1_1_1_1_0 = (CrossReference)cColumnAssignment_1_1_1_1.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_1_1_1_1_0_1 = (RuleCall)cColumnCDCrossReference_1_1_1_1_0.eContents().get(1);
		private final Assignment cXAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cXFromAndWhereClausesParserRuleCall_2_0 = (RuleCall)cXAssignment_2.eContents().get(0);
		
		//SELECT:
		//	"SELECT" ("*" | (column+=[CD] ("," column+=[CD])*)*) x=FromAndWhereClauses;
		@Override public ParserRule getRule() { return rule; }
		
		//"SELECT" ("*" | (column+=[CD] ("," column+=[CD])*)*) x=FromAndWhereClauses
		public Group getGroup() { return cGroup; }
		
		//"SELECT"
		public Keyword getSELECTKeyword_0() { return cSELECTKeyword_0; }
		
		//("*" | (column+=[CD] ("," column+=[CD])*)*)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//"*"
		public Keyword getAsteriskKeyword_1_0() { return cAsteriskKeyword_1_0; }
		
		//(column+=[CD] ("," column+=[CD])*)*
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_1_1_0() { return cColumnAssignment_1_1_0; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_1_1_0_0() { return cColumnCDCrossReference_1_1_0_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_1_1_0_0_1() { return cColumnCDIDTerminalRuleCall_1_1_0_0_1; }
		
		//("," column+=[CD])*
		public Group getGroup_1_1_1() { return cGroup_1_1_1; }
		
		//","
		public Keyword getCommaKeyword_1_1_1_0() { return cCommaKeyword_1_1_1_0; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_1_1_1_1() { return cColumnAssignment_1_1_1_1; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_1_1_1_1_0() { return cColumnCDCrossReference_1_1_1_1_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_1_1_1_1_0_1() { return cColumnCDIDTerminalRuleCall_1_1_1_1_0_1; }
		
		//x=FromAndWhereClauses
		public Assignment getXAssignment_2() { return cXAssignment_2; }
		
		//FromAndWhereClauses
		public RuleCall getXFromAndWhereClausesParserRuleCall_2_0() { return cXFromAndWhereClausesParserRuleCall_2_0; }
	}
	public class FromAndWhereClausesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.FromAndWhereClauses");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFROMKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTableTableNameCrossReference_1_0 = (CrossReference)cTableAssignment_1.eContents().get(0);
		private final RuleCall cTableTableNameIDTerminalRuleCall_1_0_1 = (RuleCall)cTableTableNameCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cWHEREKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cZAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cZWHEREParserRuleCall_2_1_0 = (RuleCall)cZAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Alternatives cAlternatives_2_2_0 = (Alternatives)cGroup_2_2.eContents().get(0);
		private final Keyword cANDKeyword_2_2_0_0 = (Keyword)cAlternatives_2_2_0.eContents().get(0);
		private final Keyword cORKeyword_2_2_0_1 = (Keyword)cAlternatives_2_2_0.eContents().get(1);
		private final Assignment cZAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cZWHEREParserRuleCall_2_2_1_0 = (RuleCall)cZAssignment_2_2_1.eContents().get(0);
		
		//FromAndWhereClauses:
		//	"FROM" table=[TableName] ("WHERE" z+=WHERE (("AND" | "OR") z+=WHERE)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//"FROM" table=[TableName] ("WHERE" z+=WHERE (("AND" | "OR") z+=WHERE)*)?
		public Group getGroup() { return cGroup; }
		
		//"FROM"
		public Keyword getFROMKeyword_0() { return cFROMKeyword_0; }
		
		//table=[TableName]
		public Assignment getTableAssignment_1() { return cTableAssignment_1; }
		
		//[TableName]
		public CrossReference getTableTableNameCrossReference_1_0() { return cTableTableNameCrossReference_1_0; }
		
		//ID
		public RuleCall getTableTableNameIDTerminalRuleCall_1_0_1() { return cTableTableNameIDTerminalRuleCall_1_0_1; }
		
		//("WHERE" z+=WHERE (("AND" | "OR") z+=WHERE)*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//"WHERE"
		public Keyword getWHEREKeyword_2_0() { return cWHEREKeyword_2_0; }
		
		//z+=WHERE
		public Assignment getZAssignment_2_1() { return cZAssignment_2_1; }
		
		//WHERE
		public RuleCall getZWHEREParserRuleCall_2_1_0() { return cZWHEREParserRuleCall_2_1_0; }
		
		//(("AND" | "OR") z+=WHERE)*
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//("AND" | "OR")
		public Alternatives getAlternatives_2_2_0() { return cAlternatives_2_2_0; }
		
		//"AND"
		public Keyword getANDKeyword_2_2_0_0() { return cANDKeyword_2_2_0_0; }
		
		//"OR"
		public Keyword getORKeyword_2_2_0_1() { return cORKeyword_2_2_0_1; }
		
		//z+=WHERE
		public Assignment getZAssignment_2_2_1() { return cZAssignment_2_2_1; }
		
		//WHERE
		public RuleCall getZWHEREParserRuleCall_2_2_1_0() { return cZWHEREParserRuleCall_2_2_1_0; }
	}
	public class WHEREElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.WHERE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cColumnAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cColumnCDCrossReference_0_0 = (CrossReference)cColumnAssignment_0.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_0_0_1 = (RuleCall)cColumnCDCrossReference_0_0.eContents().get(1);
		private final Assignment cSignAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cSignAlternatives_1_0 = (Alternatives)cSignAssignment_1.eContents().get(0);
		private final Keyword cSignEqualsSignKeyword_1_0_0 = (Keyword)cSignAlternatives_1_0.eContents().get(0);
		private final Keyword cSignLessThanSignKeyword_1_0_1 = (Keyword)cSignAlternatives_1_0.eContents().get(1);
		private final Keyword cSignLessThanSignEqualsSignKeyword_1_0_2 = (Keyword)cSignAlternatives_1_0.eContents().get(2);
		private final Keyword cSignGreaterThanSignKeyword_1_0_3 = (Keyword)cSignAlternatives_1_0.eContents().get(3);
		private final Keyword cSignGreaterThanSignEqualsSignKeyword_1_0_4 = (Keyword)cSignAlternatives_1_0.eContents().get(4);
		private final Keyword cSignExclamationMarkEqualsSignKeyword_1_0_5 = (Keyword)cSignAlternatives_1_0.eContents().get(5);
		private final Keyword cSignLIKEKeyword_1_0_6 = (Keyword)cSignAlternatives_1_0.eContents().get(6);
		private final Assignment cOperAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Alternatives cOperAlternatives_2_0 = (Alternatives)cOperAssignment_2.eContents().get(0);
		private final RuleCall cOperOper1ParserRuleCall_2_0_0 = (RuleCall)cOperAlternatives_2_0.eContents().get(0);
		private final RuleCall cOperOper2ParserRuleCall_2_0_1 = (RuleCall)cOperAlternatives_2_0.eContents().get(1);
		private final RuleCall cOperOper3ParserRuleCall_2_0_2 = (RuleCall)cOperAlternatives_2_0.eContents().get(2);
		
		//WHERE:
		//	column+=[CD] sign=("=" | "<" | "<=" | ">" | ">=" | "!=" | "LIKE") Oper=(Oper1 | Oper2 | Oper3);
		@Override public ParserRule getRule() { return rule; }
		
		//column+=[CD] sign=("=" | "<" | "<=" | ">" | ">=" | "!=" | "LIKE") Oper=(Oper1 | Oper2 | Oper3)
		public Group getGroup() { return cGroup; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_0() { return cColumnAssignment_0; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_0_0() { return cColumnCDCrossReference_0_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_0_0_1() { return cColumnCDIDTerminalRuleCall_0_0_1; }
		
		//sign=("=" | "<" | "<=" | ">" | ">=" | "!=" | "LIKE")
		public Assignment getSignAssignment_1() { return cSignAssignment_1; }
		
		//("=" | "<" | "<=" | ">" | ">=" | "!=" | "LIKE")
		public Alternatives getSignAlternatives_1_0() { return cSignAlternatives_1_0; }
		
		//"="
		public Keyword getSignEqualsSignKeyword_1_0_0() { return cSignEqualsSignKeyword_1_0_0; }
		
		//"<"
		public Keyword getSignLessThanSignKeyword_1_0_1() { return cSignLessThanSignKeyword_1_0_1; }
		
		//"<="
		public Keyword getSignLessThanSignEqualsSignKeyword_1_0_2() { return cSignLessThanSignEqualsSignKeyword_1_0_2; }
		
		//">"
		public Keyword getSignGreaterThanSignKeyword_1_0_3() { return cSignGreaterThanSignKeyword_1_0_3; }
		
		//">="
		public Keyword getSignGreaterThanSignEqualsSignKeyword_1_0_4() { return cSignGreaterThanSignEqualsSignKeyword_1_0_4; }
		
		//"!="
		public Keyword getSignExclamationMarkEqualsSignKeyword_1_0_5() { return cSignExclamationMarkEqualsSignKeyword_1_0_5; }
		
		//"LIKE"
		public Keyword getSignLIKEKeyword_1_0_6() { return cSignLIKEKeyword_1_0_6; }
		
		//Oper=(Oper1 | Oper2 | Oper3)
		public Assignment getOperAssignment_2() { return cOperAssignment_2; }
		
		//(Oper1 | Oper2 | Oper3)
		public Alternatives getOperAlternatives_2_0() { return cOperAlternatives_2_0; }
		
		//Oper1
		public RuleCall getOperOper1ParserRuleCall_2_0_0() { return cOperOper1ParserRuleCall_2_0_0; }
		
		//Oper2
		public RuleCall getOperOper2ParserRuleCall_2_0_1() { return cOperOper2ParserRuleCall_2_0_1; }
		
		//Oper3
		public RuleCall getOperOper3ParserRuleCall_2_0_2() { return cOperOper3ParserRuleCall_2_0_2; }
	}
	public class Oper1Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.Oper1");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumberSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cNumberSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Oper1:
		//	"#" name=ID "#";
		@Override public ParserRule getRule() { return rule; }
		
		//"#" name=ID "#"
		public Group getGroup() { return cGroup; }
		
		//"#"
		public Keyword getNumberSignKeyword_0() { return cNumberSignKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"#"
		public Keyword getNumberSignKeyword_2() { return cNumberSignKeyword_2; }
	}
	public class Oper2Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.Oper2");
		private final Assignment cColumnAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cColumnCDCrossReference_0 = (CrossReference)cColumnAssignment.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_0_1 = (RuleCall)cColumnCDCrossReference_0.eContents().get(1);
		
		//Oper2:
		//	column+=[CD];
		@Override public ParserRule getRule() { return rule; }
		
		//column+=[CD]
		public Assignment getColumnAssignment() { return cColumnAssignment; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_0() { return cColumnCDCrossReference_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_0_1() { return cColumnCDIDTerminalRuleCall_0_1; }
	}
	public class Oper3Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.Oper3");
		private final Assignment cValAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValINTTerminalRuleCall_0 = (RuleCall)cValAssignment.eContents().get(0);
		
		//Oper3:
		//	val=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//val=INT
		public Assignment getValAssignment() { return cValAssignment; }
		
		//INT
		public RuleCall getValINTTerminalRuleCall_0() { return cValINTTerminalRuleCall_0; }
	}
	public class DATABASEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.DATABASE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCREATEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cDATABASEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//DATABASE:
		//	"CREATE" "DATABASE" name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//"CREATE" "DATABASE" name=ID
		public Group getGroup() { return cGroup; }
		
		//"CREATE"
		public Keyword getCREATEKeyword_0() { return cCREATEKeyword_0; }
		
		//"DATABASE"
		public Keyword getDATABASEKeyword_1() { return cDATABASEKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
	}
	public class CREATEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.CREATE");
		private final Assignment cTablesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTablesTABLEParserRuleCall_0 = (RuleCall)cTablesAssignment.eContents().get(0);
		
		//CREATE:
		//	tables+=TABLE+;
		@Override public ParserRule getRule() { return rule; }
		
		//tables+=TABLE+
		public Assignment getTablesAssignment() { return cTablesAssignment; }
		
		//TABLE
		public RuleCall getTablesTABLEParserRuleCall_0() { return cTablesTABLEParserRuleCall_0; }
	}
	public class TABLEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.TABLE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCREATEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTABLEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTableAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTableTableNameParserRuleCall_2_0 = (RuleCall)cTableAssignment_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAttributesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Alternatives cAttributesAlternatives_4_0 = (Alternatives)cAttributesAssignment_4.eContents().get(0);
		private final RuleCall cAttributesColumnDeclarationParserRuleCall_4_0_0 = (RuleCall)cAttributesAlternatives_4_0.eContents().get(0);
		private final RuleCall cAttributesPrimaryKeyParserRuleCall_4_0_1 = (RuleCall)cAttributesAlternatives_4_0.eContents().get(1);
		private final RuleCall cAttributesForeignKeyParserRuleCall_4_0_2 = (RuleCall)cAttributesAlternatives_4_0.eContents().get(2);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAttributesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final Alternatives cAttributesAlternatives_5_1_0 = (Alternatives)cAttributesAssignment_5_1.eContents().get(0);
		private final RuleCall cAttributesColumnDeclarationParserRuleCall_5_1_0_0 = (RuleCall)cAttributesAlternatives_5_1_0.eContents().get(0);
		private final RuleCall cAttributesPrimaryKeyParserRuleCall_5_1_0_1 = (RuleCall)cAttributesAlternatives_5_1_0.eContents().get(1);
		private final RuleCall cAttributesForeignKeyParserRuleCall_5_1_0_2 = (RuleCall)cAttributesAlternatives_5_1_0.eContents().get(2);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//TABLE:
		//	"CREATE" "TABLE" table+=tableName "(" attributes+=(ColumnDeclaration | PrimaryKey | ForeignKey)+ (","
		//	attributes+=(ColumnDeclaration | PrimaryKey | ForeignKey))*
		//	")";
		@Override public ParserRule getRule() { return rule; }
		
		//"CREATE" "TABLE" table+=tableName "(" attributes+=(ColumnDeclaration | PrimaryKey | ForeignKey)+ (","
		//attributes+=(ColumnDeclaration | PrimaryKey | ForeignKey))* ")"
		public Group getGroup() { return cGroup; }
		
		//"CREATE"
		public Keyword getCREATEKeyword_0() { return cCREATEKeyword_0; }
		
		//"TABLE"
		public Keyword getTABLEKeyword_1() { return cTABLEKeyword_1; }
		
		//table+=tableName
		public Assignment getTableAssignment_2() { return cTableAssignment_2; }
		
		//tableName
		public RuleCall getTableTableNameParserRuleCall_2_0() { return cTableTableNameParserRuleCall_2_0; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//attributes+=(ColumnDeclaration | PrimaryKey | ForeignKey)+
		public Assignment getAttributesAssignment_4() { return cAttributesAssignment_4; }
		
		//(ColumnDeclaration | PrimaryKey | ForeignKey)
		public Alternatives getAttributesAlternatives_4_0() { return cAttributesAlternatives_4_0; }
		
		//ColumnDeclaration
		public RuleCall getAttributesColumnDeclarationParserRuleCall_4_0_0() { return cAttributesColumnDeclarationParserRuleCall_4_0_0; }
		
		//PrimaryKey
		public RuleCall getAttributesPrimaryKeyParserRuleCall_4_0_1() { return cAttributesPrimaryKeyParserRuleCall_4_0_1; }
		
		//ForeignKey
		public RuleCall getAttributesForeignKeyParserRuleCall_4_0_2() { return cAttributesForeignKeyParserRuleCall_4_0_2; }
		
		//("," attributes+=(ColumnDeclaration | PrimaryKey | ForeignKey))*
		public Group getGroup_5() { return cGroup_5; }
		
		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }
		
		//attributes+=(ColumnDeclaration | PrimaryKey | ForeignKey)
		public Assignment getAttributesAssignment_5_1() { return cAttributesAssignment_5_1; }
		
		//(ColumnDeclaration | PrimaryKey | ForeignKey)
		public Alternatives getAttributesAlternatives_5_1_0() { return cAttributesAlternatives_5_1_0; }
		
		//ColumnDeclaration
		public RuleCall getAttributesColumnDeclarationParserRuleCall_5_1_0_0() { return cAttributesColumnDeclarationParserRuleCall_5_1_0_0; }
		
		//PrimaryKey
		public RuleCall getAttributesPrimaryKeyParserRuleCall_5_1_0_1() { return cAttributesPrimaryKeyParserRuleCall_5_1_0_1; }
		
		//ForeignKey
		public RuleCall getAttributesForeignKeyParserRuleCall_5_1_0_2() { return cAttributesForeignKeyParserRuleCall_5_1_0_2; }
		
		//")"
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	public class TableNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.tableName");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//tableName TableName:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class ColumnDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.ColumnDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeDATATYPEEnumRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Assignment cNotNullAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNotNullNOTNULLTerminalRuleCall_2_0 = (RuleCall)cNotNullAssignment_2.eContents().get(0);
		
		//ColumnDeclaration CD:
		//	name=ID type=DATATYPE notNull?=NOTNULL?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID type=DATATYPE notNull?=NOTNULL?
		public Group getGroup() { return cGroup; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//type=DATATYPE
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//DATATYPE
		public RuleCall getTypeDATATYPEEnumRuleCall_1_0() { return cTypeDATATYPEEnumRuleCall_1_0; }
		
		//notNull?=NOTNULL?
		public Assignment getNotNullAssignment_2() { return cNotNullAssignment_2; }
		
		//NOTNULL
		public RuleCall getNotNullNOTNULLTerminalRuleCall_2_0() { return cNotNullNOTNULLTerminalRuleCall_2_0; }
	}
	public class PrimaryKeyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.PrimaryKey");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPRIMARYKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cKEYKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColumnAsPKAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cColumnAsPKCDCrossReference_3_0 = (CrossReference)cColumnAsPKAssignment_3.eContents().get(0);
		private final RuleCall cColumnAsPKCDIDTerminalRuleCall_3_0_1 = (RuleCall)cColumnAsPKCDCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cColumnAsPKAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cColumnAsPKCDCrossReference_4_1_0 = (CrossReference)cColumnAsPKAssignment_4_1.eContents().get(0);
		private final RuleCall cColumnAsPKCDIDTerminalRuleCall_4_1_0_1 = (RuleCall)cColumnAsPKCDCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//PrimaryKey:
		//	"PRIMARY" "KEY" "("
		//	columnAsPK+=[CD] ("," columnAsPK+=[CD])*
		//	")";
		@Override public ParserRule getRule() { return rule; }
		
		//"PRIMARY" "KEY" "(" columnAsPK+=[CD] ("," columnAsPK+=[CD])* ")"
		public Group getGroup() { return cGroup; }
		
		//"PRIMARY"
		public Keyword getPRIMARYKeyword_0() { return cPRIMARYKeyword_0; }
		
		//"KEY"
		public Keyword getKEYKeyword_1() { return cKEYKeyword_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//columnAsPK+=[CD]
		public Assignment getColumnAsPKAssignment_3() { return cColumnAsPKAssignment_3; }
		
		//[CD]
		public CrossReference getColumnAsPKCDCrossReference_3_0() { return cColumnAsPKCDCrossReference_3_0; }
		
		//ID
		public RuleCall getColumnAsPKCDIDTerminalRuleCall_3_0_1() { return cColumnAsPKCDIDTerminalRuleCall_3_0_1; }
		
		//("," columnAsPK+=[CD])*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//columnAsPK+=[CD]
		public Assignment getColumnAsPKAssignment_4_1() { return cColumnAsPKAssignment_4_1; }
		
		//[CD]
		public CrossReference getColumnAsPKCDCrossReference_4_1_0() { return cColumnAsPKCDCrossReference_4_1_0; }
		
		//ID
		public RuleCall getColumnAsPKCDIDTerminalRuleCall_4_1_0_1() { return cColumnAsPKCDIDTerminalRuleCall_4_1_0_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
	}
	public class ForeignKeyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.ForeignKey");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFOREIGNKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cKEYKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColumnAsFKAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cColumnAsFKCDCrossReference_3_0 = (CrossReference)cColumnAsFKAssignment_3.eContents().get(0);
		private final RuleCall cColumnAsFKCDIDTerminalRuleCall_3_0_1 = (RuleCall)cColumnAsFKCDCrossReference_3_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cColumnAsFKAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cColumnAsFKCDCrossReference_4_1_0 = (CrossReference)cColumnAsFKAssignment_4_1.eContents().get(0);
		private final RuleCall cColumnAsFKCDIDTerminalRuleCall_4_1_0_1 = (RuleCall)cColumnAsFKCDCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cREFERENCESKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cForeignTableAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cForeignTableTABLECrossReference_7_0 = (CrossReference)cForeignTableAssignment_7.eContents().get(0);
		private final RuleCall cForeignTableTABLEIDTerminalRuleCall_7_0_1 = (RuleCall)cForeignTableTABLECrossReference_7_0.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cForeignColumnsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final CrossReference cForeignColumnsCDCrossReference_9_0 = (CrossReference)cForeignColumnsAssignment_9.eContents().get(0);
		private final RuleCall cForeignColumnsCDIDTerminalRuleCall_9_0_1 = (RuleCall)cForeignColumnsCDCrossReference_9_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cForeignColumnsAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cForeignColumnsCDCrossReference_10_1_0 = (CrossReference)cForeignColumnsAssignment_10_1.eContents().get(0);
		private final RuleCall cForeignColumnsCDIDTerminalRuleCall_10_1_0_1 = (RuleCall)cForeignColumnsCDCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//ForeignKey:
		//	"FOREIGN" "KEY" "("
		//	columnAsFK+=[CD] ("," columnAsFK+=[CD])* ")"
		//	"REFERENCES" foreignTable=[TABLE]
		//	"(" foreignColumns+=[CD] ("," foreignColumns+=[CD])* ")";
		@Override public ParserRule getRule() { return rule; }
		
		//"FOREIGN" "KEY" "(" columnAsFK+=[CD] ("," columnAsFK+=[CD])* ")" "REFERENCES" foreignTable=[TABLE] "("
		//foreignColumns+=[CD] ("," foreignColumns+=[CD])* ")"
		public Group getGroup() { return cGroup; }
		
		//"FOREIGN"
		public Keyword getFOREIGNKeyword_0() { return cFOREIGNKeyword_0; }
		
		//"KEY"
		public Keyword getKEYKeyword_1() { return cKEYKeyword_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//columnAsFK+=[CD]
		public Assignment getColumnAsFKAssignment_3() { return cColumnAsFKAssignment_3; }
		
		//[CD]
		public CrossReference getColumnAsFKCDCrossReference_3_0() { return cColumnAsFKCDCrossReference_3_0; }
		
		//ID
		public RuleCall getColumnAsFKCDIDTerminalRuleCall_3_0_1() { return cColumnAsFKCDIDTerminalRuleCall_3_0_1; }
		
		//("," columnAsFK+=[CD])*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//columnAsFK+=[CD]
		public Assignment getColumnAsFKAssignment_4_1() { return cColumnAsFKAssignment_4_1; }
		
		//[CD]
		public CrossReference getColumnAsFKCDCrossReference_4_1_0() { return cColumnAsFKCDCrossReference_4_1_0; }
		
		//ID
		public RuleCall getColumnAsFKCDIDTerminalRuleCall_4_1_0_1() { return cColumnAsFKCDIDTerminalRuleCall_4_1_0_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//"REFERENCES"
		public Keyword getREFERENCESKeyword_6() { return cREFERENCESKeyword_6; }
		
		//foreignTable=[TABLE]
		public Assignment getForeignTableAssignment_7() { return cForeignTableAssignment_7; }
		
		//[TABLE]
		public CrossReference getForeignTableTABLECrossReference_7_0() { return cForeignTableTABLECrossReference_7_0; }
		
		//ID
		public RuleCall getForeignTableTABLEIDTerminalRuleCall_7_0_1() { return cForeignTableTABLEIDTerminalRuleCall_7_0_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_8() { return cLeftParenthesisKeyword_8; }
		
		//foreignColumns+=[CD]
		public Assignment getForeignColumnsAssignment_9() { return cForeignColumnsAssignment_9; }
		
		//[CD]
		public CrossReference getForeignColumnsCDCrossReference_9_0() { return cForeignColumnsCDCrossReference_9_0; }
		
		//ID
		public RuleCall getForeignColumnsCDIDTerminalRuleCall_9_0_1() { return cForeignColumnsCDIDTerminalRuleCall_9_0_1; }
		
		//("," foreignColumns+=[CD])*
		public Group getGroup_10() { return cGroup_10; }
		
		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }
		
		//foreignColumns+=[CD]
		public Assignment getForeignColumnsAssignment_10_1() { return cForeignColumnsAssignment_10_1; }
		
		//[CD]
		public CrossReference getForeignColumnsCDCrossReference_10_1_0() { return cForeignColumnsCDCrossReference_10_1_0; }
		
		//ID
		public RuleCall getForeignColumnsCDIDTerminalRuleCall_10_1_0_1() { return cForeignColumnsCDIDTerminalRuleCall_10_1_0_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_11() { return cRightParenthesisKeyword_11; }
	}
	public class DROPTABLEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.DROPTABLE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDROPKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTABLEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTableAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTableTableNameCrossReference_2_0 = (CrossReference)cTableAssignment_2.eContents().get(0);
		private final RuleCall cTableTableNameIDTerminalRuleCall_2_0_1 = (RuleCall)cTableTableNameCrossReference_2_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTableAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cTableTableNameCrossReference_3_1_0 = (CrossReference)cTableAssignment_3_1.eContents().get(0);
		private final RuleCall cTableTableNameIDTerminalRuleCall_3_1_0_1 = (RuleCall)cTableTableNameCrossReference_3_1_0.eContents().get(1);
		
		//DROPTABLE:
		//	"DROP" "TABLE" table+=[TableName] ("," table+=[TableName])*;
		@Override public ParserRule getRule() { return rule; }
		
		//"DROP" "TABLE" table+=[TableName] ("," table+=[TableName])*
		public Group getGroup() { return cGroup; }
		
		//"DROP"
		public Keyword getDROPKeyword_0() { return cDROPKeyword_0; }
		
		//"TABLE"
		public Keyword getTABLEKeyword_1() { return cTABLEKeyword_1; }
		
		//table+=[TableName]
		public Assignment getTableAssignment_2() { return cTableAssignment_2; }
		
		//[TableName]
		public CrossReference getTableTableNameCrossReference_2_0() { return cTableTableNameCrossReference_2_0; }
		
		//ID
		public RuleCall getTableTableNameIDTerminalRuleCall_2_0_1() { return cTableTableNameIDTerminalRuleCall_2_0_1; }
		
		//("," table+=[TableName])*
		public Group getGroup_3() { return cGroup_3; }
		
		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//table+=[TableName]
		public Assignment getTableAssignment_3_1() { return cTableAssignment_3_1; }
		
		//[TableName]
		public CrossReference getTableTableNameCrossReference_3_1_0() { return cTableTableNameCrossReference_3_1_0; }
		
		//ID
		public RuleCall getTableTableNameIDTerminalRuleCall_3_1_0_1() { return cTableTableNameIDTerminalRuleCall_3_1_0_1; }
	}
	public class TRUNCATEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.TRUNCATE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTRUNCATEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTABLEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTableAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTableTableNameCrossReference_2_0 = (CrossReference)cTableAssignment_2.eContents().get(0);
		private final RuleCall cTableTableNameIDTerminalRuleCall_2_0_1 = (RuleCall)cTableTableNameCrossReference_2_0.eContents().get(1);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTableAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cTableTableNameCrossReference_3_1_0 = (CrossReference)cTableAssignment_3_1.eContents().get(0);
		private final RuleCall cTableTableNameIDTerminalRuleCall_3_1_0_1 = (RuleCall)cTableTableNameCrossReference_3_1_0.eContents().get(1);
		
		//TRUNCATE:
		//	"TRUNCATE" "TABLE" table+=[TableName] ("," table+=[TableName])*;
		@Override public ParserRule getRule() { return rule; }
		
		//"TRUNCATE" "TABLE" table+=[TableName] ("," table+=[TableName])*
		public Group getGroup() { return cGroup; }
		
		//"TRUNCATE"
		public Keyword getTRUNCATEKeyword_0() { return cTRUNCATEKeyword_0; }
		
		//"TABLE"
		public Keyword getTABLEKeyword_1() { return cTABLEKeyword_1; }
		
		//table+=[TableName]
		public Assignment getTableAssignment_2() { return cTableAssignment_2; }
		
		//[TableName]
		public CrossReference getTableTableNameCrossReference_2_0() { return cTableTableNameCrossReference_2_0; }
		
		//ID
		public RuleCall getTableTableNameIDTerminalRuleCall_2_0_1() { return cTableTableNameIDTerminalRuleCall_2_0_1; }
		
		//("," table+=[TableName])*
		public Group getGroup_3() { return cGroup_3; }
		
		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//table+=[TableName]
		public Assignment getTableAssignment_3_1() { return cTableAssignment_3_1; }
		
		//[TableName]
		public CrossReference getTableTableNameCrossReference_3_1_0() { return cTableTableNameCrossReference_3_1_0; }
		
		//ID
		public RuleCall getTableTableNameIDTerminalRuleCall_3_1_0_1() { return cTableTableNameIDTerminalRuleCall_3_1_0_1; }
	}
	public class DELETEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.DELETE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDELETEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cXAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cXFromAndWhereClausesParserRuleCall_1_0 = (RuleCall)cXAssignment_1.eContents().get(0);
		
		//DELETE:
		//	"DELETE" x=FromAndWhereClauses;
		@Override public ParserRule getRule() { return rule; }
		
		//"DELETE" x=FromAndWhereClauses
		public Group getGroup() { return cGroup; }
		
		//"DELETE"
		public Keyword getDELETEKeyword_0() { return cDELETEKeyword_0; }
		
		//x=FromAndWhereClauses
		public Assignment getXAssignment_1() { return cXAssignment_1; }
		
		//FromAndWhereClauses
		public RuleCall getXFromAndWhereClausesParserRuleCall_1_0() { return cXFromAndWhereClausesParserRuleCall_1_0; }
	}
	public class UPDATEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.UPDATE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUPDATEKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cTableTableNameCrossReference_1_0 = (CrossReference)cTableAssignment_1.eContents().get(0);
		private final RuleCall cTableTableNameIDTerminalRuleCall_1_0_1 = (RuleCall)cTableTableNameCrossReference_1_0.eContents().get(1);
		private final Keyword cSETKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cScAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cScSetClauseParserRuleCall_3_0 = (RuleCall)cScAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cScAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cScSetClauseParserRuleCall_4_1_0 = (RuleCall)cScAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cWHEREKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cZAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cZWHEREParserRuleCall_5_1_0 = (RuleCall)cZAssignment_5_1.eContents().get(0);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Alternatives cAlternatives_5_2_0 = (Alternatives)cGroup_5_2.eContents().get(0);
		private final Keyword cANDKeyword_5_2_0_0 = (Keyword)cAlternatives_5_2_0.eContents().get(0);
		private final Keyword cORKeyword_5_2_0_1 = (Keyword)cAlternatives_5_2_0.eContents().get(1);
		private final Assignment cZAssignment_5_2_1 = (Assignment)cGroup_5_2.eContents().get(1);
		private final RuleCall cZWHEREParserRuleCall_5_2_1_0 = (RuleCall)cZAssignment_5_2_1.eContents().get(0);
		
		//UPDATE:
		//	"UPDATE" table+=[TableName] "SET" sc+=SetClause ("," sc+=SetClause)* ("WHERE" z+=WHERE (("AND" | "OR") z+=WHERE)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//"UPDATE" table+=[TableName] "SET" sc+=SetClause ("," sc+=SetClause)* ("WHERE" z+=WHERE (("AND" | "OR") z+=WHERE)*)?
		public Group getGroup() { return cGroup; }
		
		//"UPDATE"
		public Keyword getUPDATEKeyword_0() { return cUPDATEKeyword_0; }
		
		//table+=[TableName]
		public Assignment getTableAssignment_1() { return cTableAssignment_1; }
		
		//[TableName]
		public CrossReference getTableTableNameCrossReference_1_0() { return cTableTableNameCrossReference_1_0; }
		
		//ID
		public RuleCall getTableTableNameIDTerminalRuleCall_1_0_1() { return cTableTableNameIDTerminalRuleCall_1_0_1; }
		
		//"SET"
		public Keyword getSETKeyword_2() { return cSETKeyword_2; }
		
		//sc+=SetClause
		public Assignment getScAssignment_3() { return cScAssignment_3; }
		
		//SetClause
		public RuleCall getScSetClauseParserRuleCall_3_0() { return cScSetClauseParserRuleCall_3_0; }
		
		//("," sc+=SetClause)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//sc+=SetClause
		public Assignment getScAssignment_4_1() { return cScAssignment_4_1; }
		
		//SetClause
		public RuleCall getScSetClauseParserRuleCall_4_1_0() { return cScSetClauseParserRuleCall_4_1_0; }
		
		//("WHERE" z+=WHERE (("AND" | "OR") z+=WHERE)*)?
		public Group getGroup_5() { return cGroup_5; }
		
		//"WHERE"
		public Keyword getWHEREKeyword_5_0() { return cWHEREKeyword_5_0; }
		
		//z+=WHERE
		public Assignment getZAssignment_5_1() { return cZAssignment_5_1; }
		
		//WHERE
		public RuleCall getZWHEREParserRuleCall_5_1_0() { return cZWHEREParserRuleCall_5_1_0; }
		
		//(("AND" | "OR") z+=WHERE)*
		public Group getGroup_5_2() { return cGroup_5_2; }
		
		//("AND" | "OR")
		public Alternatives getAlternatives_5_2_0() { return cAlternatives_5_2_0; }
		
		//"AND"
		public Keyword getANDKeyword_5_2_0_0() { return cANDKeyword_5_2_0_0; }
		
		//"OR"
		public Keyword getORKeyword_5_2_0_1() { return cORKeyword_5_2_0_1; }
		
		//z+=WHERE
		public Assignment getZAssignment_5_2_1() { return cZAssignment_5_2_1; }
		
		//WHERE
		public RuleCall getZWHEREParserRuleCall_5_2_1_0() { return cZWHEREParserRuleCall_5_2_1_0; }
	}
	public class SetClauseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.SetClause");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cColumnAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cColumnCDCrossReference_0_0 = (CrossReference)cColumnAssignment_0.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_0_0_1 = (RuleCall)cColumnCDCrossReference_0_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Group cGroup_2_0 = (Group)cAlternatives_2.eContents().get(0);
		private final Keyword cNumberSignKeyword_2_0_0 = (Keyword)cGroup_2_0.eContents().get(0);
		private final Assignment cNameAssignment_2_0_1 = (Assignment)cGroup_2_0.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_2_0_1_0 = (RuleCall)cNameAssignment_2_0_1.eContents().get(0);
		private final Keyword cNumberSignKeyword_2_0_2 = (Keyword)cGroup_2_0.eContents().get(2);
		private final Assignment cValAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final RuleCall cValINTTerminalRuleCall_2_1_0 = (RuleCall)cValAssignment_2_1.eContents().get(0);
		
		//SetClause:
		//	column+=[CD] "=" ("#" name=ID "#" | val=INT);
		@Override public ParserRule getRule() { return rule; }
		
		//column+=[CD] "=" ("#" name=ID "#" | val=INT)
		public Group getGroup() { return cGroup; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_0() { return cColumnAssignment_0; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_0_0() { return cColumnCDCrossReference_0_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_0_0_1() { return cColumnCDIDTerminalRuleCall_0_0_1; }
		
		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }
		
		//("#" name=ID "#" | val=INT)
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//"#" name=ID "#"
		public Group getGroup_2_0() { return cGroup_2_0; }
		
		//"#"
		public Keyword getNumberSignKeyword_2_0_0() { return cNumberSignKeyword_2_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_2_0_1() { return cNameAssignment_2_0_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0_1_0() { return cNameIDTerminalRuleCall_2_0_1_0; }
		
		//"#"
		public Keyword getNumberSignKeyword_2_0_2() { return cNumberSignKeyword_2_0_2; }
		
		//val=INT
		public Assignment getValAssignment_2_1() { return cValAssignment_2_1; }
		
		//INT
		public RuleCall getValINTTerminalRuleCall_2_1_0() { return cValINTTerminalRuleCall_2_1_0; }
	}
	public class ALTERElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.ALTER");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cALTERKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTABLEKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTableAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cTableTableNameCrossReference_2_0 = (CrossReference)cTableAssignment_2.eContents().get(0);
		private final RuleCall cTableTableNameIDTerminalRuleCall_2_0_1 = (RuleCall)cTableTableNameCrossReference_2_0.eContents().get(1);
		private final Assignment cAddDropUpdateAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Alternatives cAddDropUpdateAlternatives_3_0 = (Alternatives)cAddDropUpdateAssignment_3.eContents().get(0);
		private final RuleCall cAddDropUpdateALTERDROPParserRuleCall_3_0_0 = (RuleCall)cAddDropUpdateAlternatives_3_0.eContents().get(0);
		private final RuleCall cAddDropUpdateALTERADDParserRuleCall_3_0_1 = (RuleCall)cAddDropUpdateAlternatives_3_0.eContents().get(1);
		private final RuleCall cAddDropUpdateALTERUPDATEParserRuleCall_3_0_2 = (RuleCall)cAddDropUpdateAlternatives_3_0.eContents().get(2);
		
		//ALTER:
		//	"ALTER" "TABLE" table+=[TableName] addDropUpdate=(ALTERDROP | ALTERADD | ALTERUPDATE);
		@Override public ParserRule getRule() { return rule; }
		
		//"ALTER" "TABLE" table+=[TableName] addDropUpdate=(ALTERDROP | ALTERADD | ALTERUPDATE)
		public Group getGroup() { return cGroup; }
		
		//"ALTER"
		public Keyword getALTERKeyword_0() { return cALTERKeyword_0; }
		
		//"TABLE"
		public Keyword getTABLEKeyword_1() { return cTABLEKeyword_1; }
		
		//table+=[TableName]
		public Assignment getTableAssignment_2() { return cTableAssignment_2; }
		
		//[TableName]
		public CrossReference getTableTableNameCrossReference_2_0() { return cTableTableNameCrossReference_2_0; }
		
		//ID
		public RuleCall getTableTableNameIDTerminalRuleCall_2_0_1() { return cTableTableNameIDTerminalRuleCall_2_0_1; }
		
		//addDropUpdate=(ALTERDROP | ALTERADD | ALTERUPDATE)
		public Assignment getAddDropUpdateAssignment_3() { return cAddDropUpdateAssignment_3; }
		
		//(ALTERDROP | ALTERADD | ALTERUPDATE)
		public Alternatives getAddDropUpdateAlternatives_3_0() { return cAddDropUpdateAlternatives_3_0; }
		
		//ALTERDROP
		public RuleCall getAddDropUpdateALTERDROPParserRuleCall_3_0_0() { return cAddDropUpdateALTERDROPParserRuleCall_3_0_0; }
		
		//ALTERADD
		public RuleCall getAddDropUpdateALTERADDParserRuleCall_3_0_1() { return cAddDropUpdateALTERADDParserRuleCall_3_0_1; }
		
		//ALTERUPDATE
		public RuleCall getAddDropUpdateALTERUPDATEParserRuleCall_3_0_2() { return cAddDropUpdateALTERUPDATEParserRuleCall_3_0_2; }
	}
	public class ALTERDROPElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.ALTERDROP");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDROPKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCOLUMNKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColumnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cColumnCDCrossReference_2_0 = (CrossReference)cColumnAssignment_2.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_2_0_1 = (RuleCall)cColumnCDCrossReference_2_0.eContents().get(1);
		
		//ALTERDROP:
		//	"DROP" "COLUMN" column+=[CD];
		@Override public ParserRule getRule() { return rule; }
		
		//"DROP" "COLUMN" column+=[CD]
		public Group getGroup() { return cGroup; }
		
		//"DROP"
		public Keyword getDROPKeyword_0() { return cDROPKeyword_0; }
		
		//"COLUMN"
		public Keyword getCOLUMNKeyword_1() { return cCOLUMNKeyword_1; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_2() { return cColumnAssignment_2; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_2_0() { return cColumnCDCrossReference_2_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_2_0_1() { return cColumnCDIDTerminalRuleCall_2_0_1; }
	}
	public class ALTERADDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.ALTERADD");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cADDKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cColumnAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cColumnCDCrossReference_1_0 = (CrossReference)cColumnAssignment_1.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_1_0_1 = (RuleCall)cColumnCDCrossReference_1_0.eContents().get(1);
		
		//ALTERADD:
		//	"ADD" column+=[CD];
		@Override public ParserRule getRule() { return rule; }
		
		//"ADD" column+=[CD]
		public Group getGroup() { return cGroup; }
		
		//"ADD"
		public Keyword getADDKeyword_0() { return cADDKeyword_0; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_1() { return cColumnAssignment_1; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_1_0() { return cColumnCDCrossReference_1_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_1_0_1() { return cColumnCDIDTerminalRuleCall_1_0_1; }
	}
	public class ALTERUPDATEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.ALTERUPDATE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cALTERKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCOLUMNKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColumnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final CrossReference cColumnCDCrossReference_2_0 = (CrossReference)cColumnAssignment_2.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_2_0_1 = (RuleCall)cColumnCDCrossReference_2_0.eContents().get(1);
		
		//ALTERUPDATE:
		//	"ALTER" "COLUMN" column+=[CD];
		@Override public ParserRule getRule() { return rule; }
		
		//"ALTER" "COLUMN" column+=[CD]
		public Group getGroup() { return cGroup; }
		
		//"ALTER"
		public Keyword getALTERKeyword_0() { return cALTERKeyword_0; }
		
		//"COLUMN"
		public Keyword getCOLUMNKeyword_1() { return cCOLUMNKeyword_1; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_2() { return cColumnAssignment_2; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_2_0() { return cColumnCDCrossReference_2_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_2_0_1() { return cColumnCDIDTerminalRuleCall_2_0_1; }
	}
	public class VariableDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.VariableDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueINTTerminalRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//VariableDeclaration:
		//	"var" name=ID "=" value=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//"var" name=ID "=" value=INT
		public Group getGroup() { return cGroup; }
		
		//"var"
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//value=INT
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_3_0() { return cValueINTTerminalRuleCall_3_0; }
	}
	public class IntLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.IntLiteral");
		private final Assignment cValAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValINTTerminalRuleCall_0 = (RuleCall)cValAssignment.eContents().get(0);
		
		//IntLiteral:
		//	val=INT;
		@Override public ParserRule getRule() { return rule; }
		
		//val=INT
		public Assignment getValAssignment() { return cValAssignment; }
		
		//INT
		public RuleCall getValINTTerminalRuleCall_0() { return cValINTTerminalRuleCall_0; }
	}
	public class RealLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.RealLiteral");
		private final Assignment cValAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValREALParserRuleCall_0 = (RuleCall)cValAssignment.eContents().get(0);
		
		//RealLiteral:
		//	val=REAL;
		@Override public ParserRule getRule() { return rule; }
		
		//val=REAL
		public Assignment getValAssignment() { return cValAssignment; }
		
		//REAL
		public RuleCall getValREALParserRuleCall_0() { return cValREALParserRuleCall_0; }
	}
	public class IntVarExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.IntVarExpression");
		private final Assignment cVarAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cVarVariableDeclarationCrossReference_0 = (CrossReference)cVarAssignment.eContents().get(0);
		private final RuleCall cVarVariableDeclarationIDTerminalRuleCall_0_1 = (RuleCall)cVarVariableDeclarationCrossReference_0.eContents().get(1);
		
		//IntVarExpression:
		//	var=[VariableDeclaration];
		@Override public ParserRule getRule() { return rule; }
		
		//var=[VariableDeclaration]
		public Assignment getVarAssignment() { return cVarAssignment; }
		
		//[VariableDeclaration]
		public CrossReference getVarVariableDeclarationCrossReference_0() { return cVarVariableDeclarationCrossReference_0; }
		
		//ID
		public RuleCall getVarVariableDeclarationIDTerminalRuleCall_0_1() { return cVarVariableDeclarationIDTerminalRuleCall_0_1; }
	}
	public class SELECTFUNCTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.SELECTFUNCT");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCountFunctionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAvgFunctionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSumFunctionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMinFunctionParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cMaxFunctionParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//SELECTFUNCT:
		//	=> CountFunction | AvgFunction | SumFunction | MinFunction | MaxFunction;
		@Override public ParserRule getRule() { return rule; }
		
		//=> CountFunction | AvgFunction | SumFunction | MinFunction | MaxFunction
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//=> CountFunction
		public RuleCall getCountFunctionParserRuleCall_0() { return cCountFunctionParserRuleCall_0; }
		
		//AvgFunction
		public RuleCall getAvgFunctionParserRuleCall_1() { return cAvgFunctionParserRuleCall_1; }
		
		//SumFunction
		public RuleCall getSumFunctionParserRuleCall_2() { return cSumFunctionParserRuleCall_2; }
		
		//MinFunction
		public RuleCall getMinFunctionParserRuleCall_3() { return cMinFunctionParserRuleCall_3; }
		
		//MaxFunction
		public RuleCall getMaxFunctionParserRuleCall_4() { return cMaxFunctionParserRuleCall_4; }
	}
	public class CountFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.CountFunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSELECTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cCOUNTKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColumnAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cColumnCDCrossReference_3_0 = (CrossReference)cColumnAssignment_3.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_3_0_1 = (RuleCall)cColumnCDCrossReference_3_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cXAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cXFromAndWhereClausesParserRuleCall_5_0 = (RuleCall)cXAssignment_5.eContents().get(0);
		
		//CountFunction:
		//	"SELECT" "COUNT" "(" column+=[CD] ")" x=FromAndWhereClauses;
		@Override public ParserRule getRule() { return rule; }
		
		//"SELECT" "COUNT" "(" column+=[CD] ")" x=FromAndWhereClauses
		public Group getGroup() { return cGroup; }
		
		//"SELECT"
		public Keyword getSELECTKeyword_0() { return cSELECTKeyword_0; }
		
		//"COUNT"
		public Keyword getCOUNTKeyword_1() { return cCOUNTKeyword_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_3() { return cColumnAssignment_3; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_3_0() { return cColumnCDCrossReference_3_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_3_0_1() { return cColumnCDIDTerminalRuleCall_3_0_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//x=FromAndWhereClauses
		public Assignment getXAssignment_5() { return cXAssignment_5; }
		
		//FromAndWhereClauses
		public RuleCall getXFromAndWhereClausesParserRuleCall_5_0() { return cXFromAndWhereClausesParserRuleCall_5_0; }
	}
	public class AvgFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.AvgFunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSELECTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAVGKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColumnAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cColumnCDCrossReference_3_0 = (CrossReference)cColumnAssignment_3.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_3_0_1 = (RuleCall)cColumnCDCrossReference_3_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cXAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cXFromAndWhereClausesParserRuleCall_5_0 = (RuleCall)cXAssignment_5.eContents().get(0);
		
		//AvgFunction:
		//	"SELECT" "AVG" "(" column+=[CD] ")" x=FromAndWhereClauses;
		@Override public ParserRule getRule() { return rule; }
		
		//"SELECT" "AVG" "(" column+=[CD] ")" x=FromAndWhereClauses
		public Group getGroup() { return cGroup; }
		
		//"SELECT"
		public Keyword getSELECTKeyword_0() { return cSELECTKeyword_0; }
		
		//"AVG"
		public Keyword getAVGKeyword_1() { return cAVGKeyword_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_3() { return cColumnAssignment_3; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_3_0() { return cColumnCDCrossReference_3_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_3_0_1() { return cColumnCDIDTerminalRuleCall_3_0_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//x=FromAndWhereClauses
		public Assignment getXAssignment_5() { return cXAssignment_5; }
		
		//FromAndWhereClauses
		public RuleCall getXFromAndWhereClausesParserRuleCall_5_0() { return cXFromAndWhereClausesParserRuleCall_5_0; }
	}
	public class SumFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.SumFunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSELECTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cSUMKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColumnAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cColumnCDCrossReference_3_0 = (CrossReference)cColumnAssignment_3.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_3_0_1 = (RuleCall)cColumnCDCrossReference_3_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cXAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cXFromAndWhereClausesParserRuleCall_5_0 = (RuleCall)cXAssignment_5.eContents().get(0);
		
		//SumFunction:
		//	"SELECT" "SUM" "(" column+=[CD] ")" x=FromAndWhereClauses;
		@Override public ParserRule getRule() { return rule; }
		
		//"SELECT" "SUM" "(" column+=[CD] ")" x=FromAndWhereClauses
		public Group getGroup() { return cGroup; }
		
		//"SELECT"
		public Keyword getSELECTKeyword_0() { return cSELECTKeyword_0; }
		
		//"SUM"
		public Keyword getSUMKeyword_1() { return cSUMKeyword_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_3() { return cColumnAssignment_3; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_3_0() { return cColumnCDCrossReference_3_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_3_0_1() { return cColumnCDIDTerminalRuleCall_3_0_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//x=FromAndWhereClauses
		public Assignment getXAssignment_5() { return cXAssignment_5; }
		
		//FromAndWhereClauses
		public RuleCall getXFromAndWhereClausesParserRuleCall_5_0() { return cXFromAndWhereClausesParserRuleCall_5_0; }
	}
	public class MinFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.MinFunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSELECTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMINKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColumnAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cColumnCDCrossReference_3_0 = (CrossReference)cColumnAssignment_3.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_3_0_1 = (RuleCall)cColumnCDCrossReference_3_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cXAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cXFromAndWhereClausesParserRuleCall_5_0 = (RuleCall)cXAssignment_5.eContents().get(0);
		
		//MinFunction:
		//	"SELECT" "MIN" "(" column+=[CD] ")" x=FromAndWhereClauses;
		@Override public ParserRule getRule() { return rule; }
		
		//"SELECT" "MIN" "(" column+=[CD] ")" x=FromAndWhereClauses
		public Group getGroup() { return cGroup; }
		
		//"SELECT"
		public Keyword getSELECTKeyword_0() { return cSELECTKeyword_0; }
		
		//"MIN"
		public Keyword getMINKeyword_1() { return cMINKeyword_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_3() { return cColumnAssignment_3; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_3_0() { return cColumnCDCrossReference_3_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_3_0_1() { return cColumnCDIDTerminalRuleCall_3_0_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//x=FromAndWhereClauses
		public Assignment getXAssignment_5() { return cXAssignment_5; }
		
		//FromAndWhereClauses
		public RuleCall getXFromAndWhereClausesParserRuleCall_5_0() { return cXFromAndWhereClausesParserRuleCall_5_0; }
	}
	public class MaxFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.MaxFunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSELECTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMAXKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColumnAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cColumnCDCrossReference_3_0 = (CrossReference)cColumnAssignment_3.eContents().get(0);
		private final RuleCall cColumnCDIDTerminalRuleCall_3_0_1 = (RuleCall)cColumnCDCrossReference_3_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cXAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cXFromAndWhereClausesParserRuleCall_5_0 = (RuleCall)cXAssignment_5.eContents().get(0);
		
		//MaxFunction:
		//	"SELECT" "MAX" "(" column+=[CD] ")" x=FromAndWhereClauses;
		@Override public ParserRule getRule() { return rule; }
		
		//"SELECT" "MAX" "(" column+=[CD] ")" x=FromAndWhereClauses
		public Group getGroup() { return cGroup; }
		
		//"SELECT"
		public Keyword getSELECTKeyword_0() { return cSELECTKeyword_0; }
		
		//"MAX"
		public Keyword getMAXKeyword_1() { return cMAXKeyword_1; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//column+=[CD]
		public Assignment getColumnAssignment_3() { return cColumnAssignment_3; }
		
		//[CD]
		public CrossReference getColumnCDCrossReference_3_0() { return cColumnCDCrossReference_3_0; }
		
		//ID
		public RuleCall getColumnCDIDTerminalRuleCall_3_0_1() { return cColumnCDIDTerminalRuleCall_3_0_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//x=FromAndWhereClauses
		public Assignment getXAssignment_5() { return cXAssignment_5; }
		
		//FromAndWhereClauses
		public RuleCall getXFromAndWhereClausesParserRuleCall_5_0() { return cXFromAndWhereClausesParserRuleCall_5_0; }
	}
	public class INSERTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.INSERT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cINSERTKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cINTOKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameTAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameTIDTerminalRuleCall_2_0 = (RuleCall)cNameTAssignment_2.eContents().get(0);
		private final Keyword cVALUESKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cLiteralsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLiteralsDATATYPEEnumRuleCall_5_0 = (RuleCall)cLiteralsAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//INSERT:
		//	"INSERT" "INTO" nameT=ID "VALUES" "(" literals+=DATATYPE* ")";
		@Override public ParserRule getRule() { return rule; }
		
		//"INSERT" "INTO" nameT=ID "VALUES" "(" literals+=DATATYPE* ")"
		public Group getGroup() { return cGroup; }
		
		//"INSERT"
		public Keyword getINSERTKeyword_0() { return cINSERTKeyword_0; }
		
		//"INTO"
		public Keyword getINTOKeyword_1() { return cINTOKeyword_1; }
		
		//nameT=ID
		public Assignment getNameTAssignment_2() { return cNameTAssignment_2; }
		
		//ID
		public RuleCall getNameTIDTerminalRuleCall_2_0() { return cNameTIDTerminalRuleCall_2_0; }
		
		//"VALUES"
		public Keyword getVALUESKeyword_3() { return cVALUESKeyword_3; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_4() { return cLeftParenthesisKeyword_4; }
		
		//literals+=DATATYPE*
		public Assignment getLiteralsAssignment_5() { return cLiteralsAssignment_5; }
		
		//DATATYPE
		public RuleCall getLiteralsDATATYPEEnumRuleCall_5_0() { return cLiteralsDATATYPEEnumRuleCall_5_0; }
		
		//")"
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}
	
	public class DATATYPEElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.DATATYPE");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cVARCHAREnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cVARCHARVARCHARKeyword_0_0 = (Keyword)cVARCHAREnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCHAREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCHARCharKeyword_1_0 = (Keyword)cCHAREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDATEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDATEDateKeyword_2_0 = (Keyword)cDATEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cINTEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cINTIntKeyword_3_0 = (Keyword)cINTEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cFLOATEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cFLOATFloatKeyword_4_0 = (Keyword)cFLOATEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cTIMEEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cTIMETimeKeyword_5_0 = (Keyword)cTIMEEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cTEXTEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cTEXTTextKeyword_6_0 = (Keyword)cTEXTEnumLiteralDeclaration_6.eContents().get(0);
		
		//enum DATATYPE:
		//	VARCHAR | CHAR="char" | DATE="date" | INT="int" | FLOAT="float" | TIME="time" | TEXT="text";
		public EnumRule getRule() { return rule; }
		
		//VARCHAR | CHAR="char" | DATE="date" | INT="int" | FLOAT="float" | TIME="time" | TEXT="text"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//VARCHAR
		public EnumLiteralDeclaration getVARCHAREnumLiteralDeclaration_0() { return cVARCHAREnumLiteralDeclaration_0; }
		
		//"VARCHAR"
		public Keyword getVARCHARVARCHARKeyword_0_0() { return cVARCHARVARCHARKeyword_0_0; }
		
		//CHAR="char"
		public EnumLiteralDeclaration getCHAREnumLiteralDeclaration_1() { return cCHAREnumLiteralDeclaration_1; }
		
		//"char"
		public Keyword getCHARCharKeyword_1_0() { return cCHARCharKeyword_1_0; }
		
		//DATE="date"
		public EnumLiteralDeclaration getDATEEnumLiteralDeclaration_2() { return cDATEEnumLiteralDeclaration_2; }
		
		//"date"
		public Keyword getDATEDateKeyword_2_0() { return cDATEDateKeyword_2_0; }
		
		//INT="int"
		public EnumLiteralDeclaration getINTEnumLiteralDeclaration_3() { return cINTEnumLiteralDeclaration_3; }
		
		//"int"
		public Keyword getINTIntKeyword_3_0() { return cINTIntKeyword_3_0; }
		
		//FLOAT="float"
		public EnumLiteralDeclaration getFLOATEnumLiteralDeclaration_4() { return cFLOATEnumLiteralDeclaration_4; }
		
		//"float"
		public Keyword getFLOATFloatKeyword_4_0() { return cFLOATFloatKeyword_4_0; }
		
		//TIME="time"
		public EnumLiteralDeclaration getTIMEEnumLiteralDeclaration_5() { return cTIMEEnumLiteralDeclaration_5; }
		
		//"time"
		public Keyword getTIMETimeKeyword_5_0() { return cTIMETimeKeyword_5_0; }
		
		//TEXT="text"
		public EnumLiteralDeclaration getTEXTEnumLiteralDeclaration_6() { return cTEXTEnumLiteralDeclaration_6; }
		
		//"text"
		public Keyword getTEXTTextKeyword_6_0() { return cTEXTTextKeyword_6_0; }
	}
	
	private final ModelElements pModel;
	private final ElementElements pElement;
	private final REALElements pREAL;
	private final SELECTElements pSELECT;
	private final FromAndWhereClausesElements pFromAndWhereClauses;
	private final WHEREElements pWHERE;
	private final Oper1Elements pOper1;
	private final Oper2Elements pOper2;
	private final Oper3Elements pOper3;
	private final DATABASEElements pDATABASE;
	private final CREATEElements pCREATE;
	private final TABLEElements pTABLE;
	private final TableNameElements pTableName;
	private final ColumnDeclarationElements pColumnDeclaration;
	private final PrimaryKeyElements pPrimaryKey;
	private final ForeignKeyElements pForeignKey;
	private final DROPTABLEElements pDROPTABLE;
	private final TRUNCATEElements pTRUNCATE;
	private final DELETEElements pDELETE;
	private final UPDATEElements pUPDATE;
	private final SetClauseElements pSetClause;
	private final ALTERElements pALTER;
	private final ALTERDROPElements pALTERDROP;
	private final ALTERADDElements pALTERADD;
	private final ALTERUPDATEElements pALTERUPDATE;
	private final VariableDeclarationElements pVariableDeclaration;
	private final IntLiteralElements pIntLiteral;
	private final RealLiteralElements pRealLiteral;
	private final IntVarExpressionElements pIntVarExpression;
	private final SELECTFUNCTElements pSELECTFUNCT;
	private final CountFunctionElements pCountFunction;
	private final AvgFunctionElements pAvgFunction;
	private final SumFunctionElements pSumFunction;
	private final MinFunctionElements pMinFunction;
	private final MaxFunctionElements pMaxFunction;
	private final INSERTElements pINSERT;
	private final DATATYPEElements eDATATYPE;
	private final TerminalRule tNOTNULL;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pElement = new ElementElements();
		this.pREAL = new REALElements();
		this.pSELECT = new SELECTElements();
		this.pFromAndWhereClauses = new FromAndWhereClausesElements();
		this.pWHERE = new WHEREElements();
		this.pOper1 = new Oper1Elements();
		this.pOper2 = new Oper2Elements();
		this.pOper3 = new Oper3Elements();
		this.pDATABASE = new DATABASEElements();
		this.pCREATE = new CREATEElements();
		this.pTABLE = new TABLEElements();
		this.pTableName = new TableNameElements();
		this.pColumnDeclaration = new ColumnDeclarationElements();
		this.pPrimaryKey = new PrimaryKeyElements();
		this.pForeignKey = new ForeignKeyElements();
		this.pDROPTABLE = new DROPTABLEElements();
		this.pTRUNCATE = new TRUNCATEElements();
		this.pDELETE = new DELETEElements();
		this.pUPDATE = new UPDATEElements();
		this.pSetClause = new SetClauseElements();
		this.pALTER = new ALTERElements();
		this.pALTERDROP = new ALTERDROPElements();
		this.pALTERADD = new ALTERADDElements();
		this.pALTERUPDATE = new ALTERUPDATEElements();
		this.pVariableDeclaration = new VariableDeclarationElements();
		this.pIntLiteral = new IntLiteralElements();
		this.pRealLiteral = new RealLiteralElements();
		this.pIntVarExpression = new IntVarExpressionElements();
		this.pSELECTFUNCT = new SELECTFUNCTElements();
		this.pCountFunction = new CountFunctionElements();
		this.pAvgFunction = new AvgFunctionElements();
		this.pSumFunction = new SumFunctionElements();
		this.pMinFunction = new MinFunctionElements();
		this.pMaxFunction = new MaxFunctionElements();
		this.pINSERT = new INSERTElements();
		this.eDATATYPE = new DATATYPEElements();
		this.tNOTNULL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "mydsl.MyDsl.NOTNULL");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	Element+=Element*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Element:
	//	CREATE | ALTER | INSERT | SELECT | DELETE | DROPTABLE | TRUNCATE | UPDATE | SELECTFUNCT | DATABASE |
	//	VariableDeclaration;
	public ElementElements getElementAccess() {
		return pElement;
	}
	
	public ParserRule getElementRule() {
		return getElementAccess().getRule();
	}
	
	//REAL ecore::EFloat hidden():
	//	INT? "." INT;
	public REALElements getREALAccess() {
		return pREAL;
	}
	
	public ParserRule getREALRule() {
		return getREALAccess().getRule();
	}
	
	//SELECT:
	//	"SELECT" ("*" | (column+=[CD] ("," column+=[CD])*)*) x=FromAndWhereClauses;
	public SELECTElements getSELECTAccess() {
		return pSELECT;
	}
	
	public ParserRule getSELECTRule() {
		return getSELECTAccess().getRule();
	}
	
	//FromAndWhereClauses:
	//	"FROM" table=[TableName] ("WHERE" z+=WHERE (("AND" | "OR") z+=WHERE)*)?;
	public FromAndWhereClausesElements getFromAndWhereClausesAccess() {
		return pFromAndWhereClauses;
	}
	
	public ParserRule getFromAndWhereClausesRule() {
		return getFromAndWhereClausesAccess().getRule();
	}
	
	//WHERE:
	//	column+=[CD] sign=("=" | "<" | "<=" | ">" | ">=" | "!=" | "LIKE") Oper=(Oper1 | Oper2 | Oper3);
	public WHEREElements getWHEREAccess() {
		return pWHERE;
	}
	
	public ParserRule getWHERERule() {
		return getWHEREAccess().getRule();
	}
	
	//Oper1:
	//	"#" name=ID "#";
	public Oper1Elements getOper1Access() {
		return pOper1;
	}
	
	public ParserRule getOper1Rule() {
		return getOper1Access().getRule();
	}
	
	//Oper2:
	//	column+=[CD];
	public Oper2Elements getOper2Access() {
		return pOper2;
	}
	
	public ParserRule getOper2Rule() {
		return getOper2Access().getRule();
	}
	
	//Oper3:
	//	val=INT;
	public Oper3Elements getOper3Access() {
		return pOper3;
	}
	
	public ParserRule getOper3Rule() {
		return getOper3Access().getRule();
	}
	
	//DATABASE:
	//	"CREATE" "DATABASE" name=ID;
	public DATABASEElements getDATABASEAccess() {
		return pDATABASE;
	}
	
	public ParserRule getDATABASERule() {
		return getDATABASEAccess().getRule();
	}
	
	//CREATE:
	//	tables+=TABLE+;
	public CREATEElements getCREATEAccess() {
		return pCREATE;
	}
	
	public ParserRule getCREATERule() {
		return getCREATEAccess().getRule();
	}
	
	//TABLE:
	//	"CREATE" "TABLE" table+=tableName "(" attributes+=(ColumnDeclaration | PrimaryKey | ForeignKey)+ (","
	//	attributes+=(ColumnDeclaration | PrimaryKey | ForeignKey))*
	//	")";
	public TABLEElements getTABLEAccess() {
		return pTABLE;
	}
	
	public ParserRule getTABLERule() {
		return getTABLEAccess().getRule();
	}
	
	//tableName TableName:
	//	name=ID;
	public TableNameElements getTableNameAccess() {
		return pTableName;
	}
	
	public ParserRule getTableNameRule() {
		return getTableNameAccess().getRule();
	}
	
	//ColumnDeclaration CD:
	//	name=ID type=DATATYPE notNull?=NOTNULL?;
	public ColumnDeclarationElements getColumnDeclarationAccess() {
		return pColumnDeclaration;
	}
	
	public ParserRule getColumnDeclarationRule() {
		return getColumnDeclarationAccess().getRule();
	}
	
	//PrimaryKey:
	//	"PRIMARY" "KEY" "("
	//	columnAsPK+=[CD] ("," columnAsPK+=[CD])*
	//	")";
	public PrimaryKeyElements getPrimaryKeyAccess() {
		return pPrimaryKey;
	}
	
	public ParserRule getPrimaryKeyRule() {
		return getPrimaryKeyAccess().getRule();
	}
	
	//ForeignKey:
	//	"FOREIGN" "KEY" "("
	//	columnAsFK+=[CD] ("," columnAsFK+=[CD])* ")"
	//	"REFERENCES" foreignTable=[TABLE]
	//	"(" foreignColumns+=[CD] ("," foreignColumns+=[CD])* ")";
	public ForeignKeyElements getForeignKeyAccess() {
		return pForeignKey;
	}
	
	public ParserRule getForeignKeyRule() {
		return getForeignKeyAccess().getRule();
	}
	
	//DROPTABLE:
	//	"DROP" "TABLE" table+=[TableName] ("," table+=[TableName])*;
	public DROPTABLEElements getDROPTABLEAccess() {
		return pDROPTABLE;
	}
	
	public ParserRule getDROPTABLERule() {
		return getDROPTABLEAccess().getRule();
	}
	
	//TRUNCATE:
	//	"TRUNCATE" "TABLE" table+=[TableName] ("," table+=[TableName])*;
	public TRUNCATEElements getTRUNCATEAccess() {
		return pTRUNCATE;
	}
	
	public ParserRule getTRUNCATERule() {
		return getTRUNCATEAccess().getRule();
	}
	
	//DELETE:
	//	"DELETE" x=FromAndWhereClauses;
	public DELETEElements getDELETEAccess() {
		return pDELETE;
	}
	
	public ParserRule getDELETERule() {
		return getDELETEAccess().getRule();
	}
	
	//UPDATE:
	//	"UPDATE" table+=[TableName] "SET" sc+=SetClause ("," sc+=SetClause)* ("WHERE" z+=WHERE (("AND" | "OR") z+=WHERE)*)?;
	public UPDATEElements getUPDATEAccess() {
		return pUPDATE;
	}
	
	public ParserRule getUPDATERule() {
		return getUPDATEAccess().getRule();
	}
	
	//SetClause:
	//	column+=[CD] "=" ("#" name=ID "#" | val=INT);
	public SetClauseElements getSetClauseAccess() {
		return pSetClause;
	}
	
	public ParserRule getSetClauseRule() {
		return getSetClauseAccess().getRule();
	}
	
	//ALTER:
	//	"ALTER" "TABLE" table+=[TableName] addDropUpdate=(ALTERDROP | ALTERADD | ALTERUPDATE);
	public ALTERElements getALTERAccess() {
		return pALTER;
	}
	
	public ParserRule getALTERRule() {
		return getALTERAccess().getRule();
	}
	
	//ALTERDROP:
	//	"DROP" "COLUMN" column+=[CD];
	public ALTERDROPElements getALTERDROPAccess() {
		return pALTERDROP;
	}
	
	public ParserRule getALTERDROPRule() {
		return getALTERDROPAccess().getRule();
	}
	
	//ALTERADD:
	//	"ADD" column+=[CD];
	public ALTERADDElements getALTERADDAccess() {
		return pALTERADD;
	}
	
	public ParserRule getALTERADDRule() {
		return getALTERADDAccess().getRule();
	}
	
	//ALTERUPDATE:
	//	"ALTER" "COLUMN" column+=[CD];
	public ALTERUPDATEElements getALTERUPDATEAccess() {
		return pALTERUPDATE;
	}
	
	public ParserRule getALTERUPDATERule() {
		return getALTERUPDATEAccess().getRule();
	}
	
	//VariableDeclaration:
	//	"var" name=ID "=" value=INT;
	public VariableDeclarationElements getVariableDeclarationAccess() {
		return pVariableDeclaration;
	}
	
	public ParserRule getVariableDeclarationRule() {
		return getVariableDeclarationAccess().getRule();
	}
	
	//IntLiteral:
	//	val=INT;
	public IntLiteralElements getIntLiteralAccess() {
		return pIntLiteral;
	}
	
	public ParserRule getIntLiteralRule() {
		return getIntLiteralAccess().getRule();
	}
	
	//RealLiteral:
	//	val=REAL;
	public RealLiteralElements getRealLiteralAccess() {
		return pRealLiteral;
	}
	
	public ParserRule getRealLiteralRule() {
		return getRealLiteralAccess().getRule();
	}
	
	//IntVarExpression:
	//	var=[VariableDeclaration];
	public IntVarExpressionElements getIntVarExpressionAccess() {
		return pIntVarExpression;
	}
	
	public ParserRule getIntVarExpressionRule() {
		return getIntVarExpressionAccess().getRule();
	}
	
	//SELECTFUNCT:
	//	=> CountFunction | AvgFunction | SumFunction | MinFunction | MaxFunction;
	public SELECTFUNCTElements getSELECTFUNCTAccess() {
		return pSELECTFUNCT;
	}
	
	public ParserRule getSELECTFUNCTRule() {
		return getSELECTFUNCTAccess().getRule();
	}
	
	//CountFunction:
	//	"SELECT" "COUNT" "(" column+=[CD] ")" x=FromAndWhereClauses;
	public CountFunctionElements getCountFunctionAccess() {
		return pCountFunction;
	}
	
	public ParserRule getCountFunctionRule() {
		return getCountFunctionAccess().getRule();
	}
	
	//AvgFunction:
	//	"SELECT" "AVG" "(" column+=[CD] ")" x=FromAndWhereClauses;
	public AvgFunctionElements getAvgFunctionAccess() {
		return pAvgFunction;
	}
	
	public ParserRule getAvgFunctionRule() {
		return getAvgFunctionAccess().getRule();
	}
	
	//SumFunction:
	//	"SELECT" "SUM" "(" column+=[CD] ")" x=FromAndWhereClauses;
	public SumFunctionElements getSumFunctionAccess() {
		return pSumFunction;
	}
	
	public ParserRule getSumFunctionRule() {
		return getSumFunctionAccess().getRule();
	}
	
	//MinFunction:
	//	"SELECT" "MIN" "(" column+=[CD] ")" x=FromAndWhereClauses;
	public MinFunctionElements getMinFunctionAccess() {
		return pMinFunction;
	}
	
	public ParserRule getMinFunctionRule() {
		return getMinFunctionAccess().getRule();
	}
	
	//MaxFunction:
	//	"SELECT" "MAX" "(" column+=[CD] ")" x=FromAndWhereClauses;
	public MaxFunctionElements getMaxFunctionAccess() {
		return pMaxFunction;
	}
	
	public ParserRule getMaxFunctionRule() {
		return getMaxFunctionAccess().getRule();
	}
	
	//INSERT:
	//	"INSERT" "INTO" nameT=ID "VALUES" "(" literals+=DATATYPE* ")";
	public INSERTElements getINSERTAccess() {
		return pINSERT;
	}
	
	public ParserRule getINSERTRule() {
		return getINSERTAccess().getRule();
	}
	
	//enum DATATYPE:
	//	VARCHAR | CHAR="char" | DATE="date" | INT="int" | FLOAT="float" | TIME="time" | TEXT="text";
	public DATATYPEElements getDATATYPEAccess() {
		return eDATATYPE;
	}
	
	public EnumRule getDATATYPERule() {
		return getDATATYPEAccess().getRule();
	}
	
	//terminal NOTNULL:
	//	"not null";
	public TerminalRule getNOTNULLRule() {
		return tNOTNULL;
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
