/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl.util;

import mydsl.myDsl.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see mydsl.myDsl.MyDslPackage
 * @generated
 */
public class MyDslAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static MyDslPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyDslAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = MyDslPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MyDslSwitch<Adapter> modelSwitch =
    new MyDslSwitch<Adapter>()
    {
      @Override
      public Adapter caseModel(Model object)
      {
        return createModelAdapter();
      }
      @Override
      public Adapter caseElement(Element object)
      {
        return createElementAdapter();
      }
      @Override
      public Adapter caseSELECT(SELECT object)
      {
        return createSELECTAdapter();
      }
      @Override
      public Adapter caseFromAndWhereClauses(FromAndWhereClauses object)
      {
        return createFromAndWhereClausesAdapter();
      }
      @Override
      public Adapter caseWHERE(WHERE object)
      {
        return createWHEREAdapter();
      }
      @Override
      public Adapter caseOper1(Oper1 object)
      {
        return createOper1Adapter();
      }
      @Override
      public Adapter caseOper2(Oper2 object)
      {
        return createOper2Adapter();
      }
      @Override
      public Adapter caseOper3(Oper3 object)
      {
        return createOper3Adapter();
      }
      @Override
      public Adapter caseDATABASE(DATABASE object)
      {
        return createDATABASEAdapter();
      }
      @Override
      public Adapter caseCREATE(CREATE object)
      {
        return createCREATEAdapter();
      }
      @Override
      public Adapter caseTABLE(TABLE object)
      {
        return createTABLEAdapter();
      }
      @Override
      public Adapter caseTableName(TableName object)
      {
        return createTableNameAdapter();
      }
      @Override
      public Adapter caseCD(CD object)
      {
        return createCDAdapter();
      }
      @Override
      public Adapter casePrimaryKey(PrimaryKey object)
      {
        return createPrimaryKeyAdapter();
      }
      @Override
      public Adapter caseForeignKey(ForeignKey object)
      {
        return createForeignKeyAdapter();
      }
      @Override
      public Adapter caseDROPTABLE(DROPTABLE object)
      {
        return createDROPTABLEAdapter();
      }
      @Override
      public Adapter caseTRUNCATE(TRUNCATE object)
      {
        return createTRUNCATEAdapter();
      }
      @Override
      public Adapter caseDELETE(DELETE object)
      {
        return createDELETEAdapter();
      }
      @Override
      public Adapter caseUPDATE(UPDATE object)
      {
        return createUPDATEAdapter();
      }
      @Override
      public Adapter caseSetClause(SetClause object)
      {
        return createSetClauseAdapter();
      }
      @Override
      public Adapter caseALTER(ALTER object)
      {
        return createALTERAdapter();
      }
      @Override
      public Adapter caseALTERDROP(ALTERDROP object)
      {
        return createALTERDROPAdapter();
      }
      @Override
      public Adapter caseALTERADD(ALTERADD object)
      {
        return createALTERADDAdapter();
      }
      @Override
      public Adapter caseALTERUPDATE(ALTERUPDATE object)
      {
        return createALTERUPDATEAdapter();
      }
      @Override
      public Adapter caseVariableDeclaration(VariableDeclaration object)
      {
        return createVariableDeclarationAdapter();
      }
      @Override
      public Adapter caseIntLiteral(IntLiteral object)
      {
        return createIntLiteralAdapter();
      }
      @Override
      public Adapter caseRealLiteral(RealLiteral object)
      {
        return createRealLiteralAdapter();
      }
      @Override
      public Adapter caseIntVarExpression(IntVarExpression object)
      {
        return createIntVarExpressionAdapter();
      }
      @Override
      public Adapter caseSELECTFUNCT(SELECTFUNCT object)
      {
        return createSELECTFUNCTAdapter();
      }
      @Override
      public Adapter caseCountFunction(CountFunction object)
      {
        return createCountFunctionAdapter();
      }
      @Override
      public Adapter caseAvgFunction(AvgFunction object)
      {
        return createAvgFunctionAdapter();
      }
      @Override
      public Adapter caseSumFunction(SumFunction object)
      {
        return createSumFunctionAdapter();
      }
      @Override
      public Adapter caseMinFunction(MinFunction object)
      {
        return createMinFunctionAdapter();
      }
      @Override
      public Adapter caseMaxFunction(MaxFunction object)
      {
        return createMaxFunctionAdapter();
      }
      @Override
      public Adapter caseINSERT(INSERT object)
      {
        return createINSERTAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.Model
   * @generated
   */
  public Adapter createModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.Element
   * @generated
   */
  public Adapter createElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.SELECT <em>SELECT</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.SELECT
   * @generated
   */
  public Adapter createSELECTAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.FromAndWhereClauses <em>From And Where Clauses</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.FromAndWhereClauses
   * @generated
   */
  public Adapter createFromAndWhereClausesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.WHERE <em>WHERE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.WHERE
   * @generated
   */
  public Adapter createWHEREAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.Oper1 <em>Oper1</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.Oper1
   * @generated
   */
  public Adapter createOper1Adapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.Oper2 <em>Oper2</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.Oper2
   * @generated
   */
  public Adapter createOper2Adapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.Oper3 <em>Oper3</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.Oper3
   * @generated
   */
  public Adapter createOper3Adapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.DATABASE <em>DATABASE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.DATABASE
   * @generated
   */
  public Adapter createDATABASEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.CREATE <em>CREATE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.CREATE
   * @generated
   */
  public Adapter createCREATEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.TABLE <em>TABLE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.TABLE
   * @generated
   */
  public Adapter createTABLEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.TableName <em>Table Name</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.TableName
   * @generated
   */
  public Adapter createTableNameAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.CD <em>CD</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.CD
   * @generated
   */
  public Adapter createCDAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.PrimaryKey <em>Primary Key</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.PrimaryKey
   * @generated
   */
  public Adapter createPrimaryKeyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.ForeignKey <em>Foreign Key</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.ForeignKey
   * @generated
   */
  public Adapter createForeignKeyAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.DROPTABLE <em>DROPTABLE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.DROPTABLE
   * @generated
   */
  public Adapter createDROPTABLEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.TRUNCATE <em>TRUNCATE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.TRUNCATE
   * @generated
   */
  public Adapter createTRUNCATEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.DELETE <em>DELETE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.DELETE
   * @generated
   */
  public Adapter createDELETEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.UPDATE <em>UPDATE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.UPDATE
   * @generated
   */
  public Adapter createUPDATEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.SetClause <em>Set Clause</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.SetClause
   * @generated
   */
  public Adapter createSetClauseAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.ALTER <em>ALTER</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.ALTER
   * @generated
   */
  public Adapter createALTERAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.ALTERDROP <em>ALTERDROP</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.ALTERDROP
   * @generated
   */
  public Adapter createALTERDROPAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.ALTERADD <em>ALTERADD</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.ALTERADD
   * @generated
   */
  public Adapter createALTERADDAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.ALTERUPDATE <em>ALTERUPDATE</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.ALTERUPDATE
   * @generated
   */
  public Adapter createALTERUPDATEAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.VariableDeclaration
   * @generated
   */
  public Adapter createVariableDeclarationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.IntLiteral
   * @generated
   */
  public Adapter createIntLiteralAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.RealLiteral <em>Real Literal</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.RealLiteral
   * @generated
   */
  public Adapter createRealLiteralAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.IntVarExpression <em>Int Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.IntVarExpression
   * @generated
   */
  public Adapter createIntVarExpressionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.SELECTFUNCT <em>SELECTFUNCT</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.SELECTFUNCT
   * @generated
   */
  public Adapter createSELECTFUNCTAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.CountFunction <em>Count Function</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.CountFunction
   * @generated
   */
  public Adapter createCountFunctionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.AvgFunction <em>Avg Function</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.AvgFunction
   * @generated
   */
  public Adapter createAvgFunctionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.SumFunction <em>Sum Function</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.SumFunction
   * @generated
   */
  public Adapter createSumFunctionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.MinFunction <em>Min Function</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.MinFunction
   * @generated
   */
  public Adapter createMinFunctionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.MaxFunction <em>Max Function</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.MaxFunction
   * @generated
   */
  public Adapter createMaxFunctionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link mydsl.myDsl.INSERT <em>INSERT</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see mydsl.myDsl.INSERT
   * @generated
   */
  public Adapter createINSERTAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //MyDslAdapterFactory
