/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl.impl;

import java.util.Collection;

import mydsl.myDsl.CD;
import mydsl.myDsl.ForeignKey;
import mydsl.myDsl.MyDslPackage;
import mydsl.myDsl.TABLE;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectResolvingEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Foreign Key</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.impl.ForeignKeyImpl#getColumnAsFK <em>Column As FK</em>}</li>
 *   <li>{@link mydsl.myDsl.impl.ForeignKeyImpl#getForeignTable <em>Foreign Table</em>}</li>
 *   <li>{@link mydsl.myDsl.impl.ForeignKeyImpl#getForeignColumns <em>Foreign Columns</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ForeignKeyImpl extends MinimalEObjectImpl.Container implements ForeignKey
{
  /**
   * The cached value of the '{@link #getColumnAsFK() <em>Column As FK</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumnAsFK()
   * @generated
   * @ordered
   */
  protected EList<CD> columnAsFK;

  /**
   * The cached value of the '{@link #getForeignTable() <em>Foreign Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForeignTable()
   * @generated
   * @ordered
   */
  protected TABLE foreignTable;

  /**
   * The cached value of the '{@link #getForeignColumns() <em>Foreign Columns</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForeignColumns()
   * @generated
   * @ordered
   */
  protected EList<CD> foreignColumns;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ForeignKeyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.FOREIGN_KEY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CD> getColumnAsFK()
  {
    if (columnAsFK == null)
    {
      columnAsFK = new EObjectResolvingEList<CD>(CD.class, this, MyDslPackage.FOREIGN_KEY__COLUMN_AS_FK);
    }
    return columnAsFK;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TABLE getForeignTable()
  {
    if (foreignTable != null && foreignTable.eIsProxy())
    {
      InternalEObject oldForeignTable = (InternalEObject)foreignTable;
      foreignTable = (TABLE)eResolveProxy(oldForeignTable);
      if (foreignTable != oldForeignTable)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.FOREIGN_KEY__FOREIGN_TABLE, oldForeignTable, foreignTable));
      }
    }
    return foreignTable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TABLE basicGetForeignTable()
  {
    return foreignTable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setForeignTable(TABLE newForeignTable)
  {
    TABLE oldForeignTable = foreignTable;
    foreignTable = newForeignTable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FOREIGN_KEY__FOREIGN_TABLE, oldForeignTable, foreignTable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CD> getForeignColumns()
  {
    if (foreignColumns == null)
    {
      foreignColumns = new EObjectResolvingEList<CD>(CD.class, this, MyDslPackage.FOREIGN_KEY__FOREIGN_COLUMNS);
    }
    return foreignColumns;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.FOREIGN_KEY__COLUMN_AS_FK:
        return getColumnAsFK();
      case MyDslPackage.FOREIGN_KEY__FOREIGN_TABLE:
        if (resolve) return getForeignTable();
        return basicGetForeignTable();
      case MyDslPackage.FOREIGN_KEY__FOREIGN_COLUMNS:
        return getForeignColumns();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.FOREIGN_KEY__COLUMN_AS_FK:
        getColumnAsFK().clear();
        getColumnAsFK().addAll((Collection<? extends CD>)newValue);
        return;
      case MyDslPackage.FOREIGN_KEY__FOREIGN_TABLE:
        setForeignTable((TABLE)newValue);
        return;
      case MyDslPackage.FOREIGN_KEY__FOREIGN_COLUMNS:
        getForeignColumns().clear();
        getForeignColumns().addAll((Collection<? extends CD>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FOREIGN_KEY__COLUMN_AS_FK:
        getColumnAsFK().clear();
        return;
      case MyDslPackage.FOREIGN_KEY__FOREIGN_TABLE:
        setForeignTable((TABLE)null);
        return;
      case MyDslPackage.FOREIGN_KEY__FOREIGN_COLUMNS:
        getForeignColumns().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FOREIGN_KEY__COLUMN_AS_FK:
        return columnAsFK != null && !columnAsFK.isEmpty();
      case MyDslPackage.FOREIGN_KEY__FOREIGN_TABLE:
        return foreignTable != null;
      case MyDslPackage.FOREIGN_KEY__FOREIGN_COLUMNS:
        return foreignColumns != null && !foreignColumns.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ForeignKeyImpl
