/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl.impl;

import java.util.Collection;

import mydsl.myDsl.FromAndWhereClauses;
import mydsl.myDsl.MyDslPackage;
import mydsl.myDsl.TableName;
import mydsl.myDsl.WHERE;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>From And Where Clauses</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.impl.FromAndWhereClausesImpl#getTable <em>Table</em>}</li>
 *   <li>{@link mydsl.myDsl.impl.FromAndWhereClausesImpl#getZ <em>Z</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FromAndWhereClausesImpl extends MinimalEObjectImpl.Container implements FromAndWhereClauses
{
  /**
   * The cached value of the '{@link #getTable() <em>Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTable()
   * @generated
   * @ordered
   */
  protected TableName table;

  /**
   * The cached value of the '{@link #getZ() <em>Z</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZ()
   * @generated
   * @ordered
   */
  protected EList<WHERE> z;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FromAndWhereClausesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.FROM_AND_WHERE_CLAUSES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TableName getTable()
  {
    if (table != null && table.eIsProxy())
    {
      InternalEObject oldTable = (InternalEObject)table;
      table = (TableName)eResolveProxy(oldTable);
      if (table != oldTable)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.FROM_AND_WHERE_CLAUSES__TABLE, oldTable, table));
      }
    }
    return table;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TableName basicGetTable()
  {
    return table;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTable(TableName newTable)
  {
    TableName oldTable = table;
    table = newTable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.FROM_AND_WHERE_CLAUSES__TABLE, oldTable, table));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WHERE> getZ()
  {
    if (z == null)
    {
      z = new EObjectContainmentEList<WHERE>(WHERE.class, this, MyDslPackage.FROM_AND_WHERE_CLAUSES__Z);
    }
    return z;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.FROM_AND_WHERE_CLAUSES__Z:
        return ((InternalEList<?>)getZ()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.FROM_AND_WHERE_CLAUSES__TABLE:
        if (resolve) return getTable();
        return basicGetTable();
      case MyDslPackage.FROM_AND_WHERE_CLAUSES__Z:
        return getZ();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.FROM_AND_WHERE_CLAUSES__TABLE:
        setTable((TableName)newValue);
        return;
      case MyDslPackage.FROM_AND_WHERE_CLAUSES__Z:
        getZ().clear();
        getZ().addAll((Collection<? extends WHERE>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FROM_AND_WHERE_CLAUSES__TABLE:
        setTable((TableName)null);
        return;
      case MyDslPackage.FROM_AND_WHERE_CLAUSES__Z:
        getZ().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.FROM_AND_WHERE_CLAUSES__TABLE:
        return table != null;
      case MyDslPackage.FROM_AND_WHERE_CLAUSES__Z:
        return z != null && !z.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //FromAndWhereClausesImpl
