/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl.impl;

import java.util.Collection;

import mydsl.myDsl.DATATYPE;
import mydsl.myDsl.INSERT;
import mydsl.myDsl.MyDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>INSERT</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.impl.INSERTImpl#getNameT <em>Name T</em>}</li>
 *   <li>{@link mydsl.myDsl.impl.INSERTImpl#getLiterals <em>Literals</em>}</li>
 * </ul>
 *
 * @generated
 */
public class INSERTImpl extends ElementImpl implements INSERT
{
  /**
   * The default value of the '{@link #getNameT() <em>Name T</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameT()
   * @generated
   * @ordered
   */
  protected static final String NAME_T_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getNameT() <em>Name T</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNameT()
   * @generated
   * @ordered
   */
  protected String nameT = NAME_T_EDEFAULT;

  /**
   * The cached value of the '{@link #getLiterals() <em>Literals</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLiterals()
   * @generated
   * @ordered
   */
  protected EList<DATATYPE> literals;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected INSERTImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.INSERT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getNameT()
  {
    return nameT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNameT(String newNameT)
  {
    String oldNameT = nameT;
    nameT = newNameT;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INSERT__NAME_T, oldNameT, nameT));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DATATYPE> getLiterals()
  {
    if (literals == null)
    {
      literals = new EDataTypeEList<DATATYPE>(DATATYPE.class, this, MyDslPackage.INSERT__LITERALS);
    }
    return literals;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.INSERT__NAME_T:
        return getNameT();
      case MyDslPackage.INSERT__LITERALS:
        return getLiterals();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.INSERT__NAME_T:
        setNameT((String)newValue);
        return;
      case MyDslPackage.INSERT__LITERALS:
        getLiterals().clear();
        getLiterals().addAll((Collection<? extends DATATYPE>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INSERT__NAME_T:
        setNameT(NAME_T_EDEFAULT);
        return;
      case MyDslPackage.INSERT__LITERALS:
        getLiterals().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INSERT__NAME_T:
        return NAME_T_EDEFAULT == null ? nameT != null : !NAME_T_EDEFAULT.equals(nameT);
      case MyDslPackage.INSERT__LITERALS:
        return literals != null && !literals.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nameT: ");
    result.append(nameT);
    result.append(", literals: ");
    result.append(literals);
    result.append(')');
    return result.toString();
  }

} //INSERTImpl
