/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl.impl;

import mydsl.myDsl.MaxFunction;
import mydsl.myDsl.MyDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Max Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MaxFunctionImpl extends SELECTFUNCTImpl implements MaxFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MaxFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.MAX_FUNCTION;
  }

} //MaxFunctionImpl
