/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl.impl;

import mydsl.myDsl.MinFunction;
import mydsl.myDsl.MyDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Min Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MinFunctionImpl extends SELECTFUNCTImpl implements MinFunction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MinFunctionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.MIN_FUNCTION;
  }

} //MinFunctionImpl
