/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl.impl;

import mydsl.myDsl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyDslFactoryImpl extends EFactoryImpl implements MyDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static MyDslFactory init()
  {
    try
    {
      MyDslFactory theMyDslFactory = (MyDslFactory)EPackage.Registry.INSTANCE.getEFactory(MyDslPackage.eNS_URI);
      if (theMyDslFactory != null)
      {
        return theMyDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new MyDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case MyDslPackage.MODEL: return createModel();
      case MyDslPackage.ELEMENT: return createElement();
      case MyDslPackage.SELECT: return createSELECT();
      case MyDslPackage.FROM_AND_WHERE_CLAUSES: return createFromAndWhereClauses();
      case MyDslPackage.WHERE: return createWHERE();
      case MyDslPackage.OPER1: return createOper1();
      case MyDslPackage.OPER2: return createOper2();
      case MyDslPackage.OPER3: return createOper3();
      case MyDslPackage.DATABASE: return createDATABASE();
      case MyDslPackage.CREATE: return createCREATE();
      case MyDslPackage.TABLE: return createTABLE();
      case MyDslPackage.TABLE_NAME: return createTableName();
      case MyDslPackage.CD: return createCD();
      case MyDslPackage.PRIMARY_KEY: return createPrimaryKey();
      case MyDslPackage.FOREIGN_KEY: return createForeignKey();
      case MyDslPackage.DROPTABLE: return createDROPTABLE();
      case MyDslPackage.TRUNCATE: return createTRUNCATE();
      case MyDslPackage.DELETE: return createDELETE();
      case MyDslPackage.UPDATE: return createUPDATE();
      case MyDslPackage.SET_CLAUSE: return createSetClause();
      case MyDslPackage.ALTER: return createALTER();
      case MyDslPackage.ALTERDROP: return createALTERDROP();
      case MyDslPackage.ALTERADD: return createALTERADD();
      case MyDslPackage.ALTERUPDATE: return createALTERUPDATE();
      case MyDslPackage.VARIABLE_DECLARATION: return createVariableDeclaration();
      case MyDslPackage.INT_LITERAL: return createIntLiteral();
      case MyDslPackage.REAL_LITERAL: return createRealLiteral();
      case MyDslPackage.INT_VAR_EXPRESSION: return createIntVarExpression();
      case MyDslPackage.SELECTFUNCT: return createSELECTFUNCT();
      case MyDslPackage.COUNT_FUNCTION: return createCountFunction();
      case MyDslPackage.AVG_FUNCTION: return createAvgFunction();
      case MyDslPackage.SUM_FUNCTION: return createSumFunction();
      case MyDslPackage.MIN_FUNCTION: return createMinFunction();
      case MyDslPackage.MAX_FUNCTION: return createMaxFunction();
      case MyDslPackage.INSERT: return createINSERT();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case MyDslPackage.DATATYPE:
        return createDATATYPEFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case MyDslPackage.DATATYPE:
        return convertDATATYPEToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Element createElement()
  {
    ElementImpl element = new ElementImpl();
    return element;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SELECT createSELECT()
  {
    SELECTImpl select = new SELECTImpl();
    return select;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FromAndWhereClauses createFromAndWhereClauses()
  {
    FromAndWhereClausesImpl fromAndWhereClauses = new FromAndWhereClausesImpl();
    return fromAndWhereClauses;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WHERE createWHERE()
  {
    WHEREImpl where = new WHEREImpl();
    return where;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Oper1 createOper1()
  {
    Oper1Impl oper1 = new Oper1Impl();
    return oper1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Oper2 createOper2()
  {
    Oper2Impl oper2 = new Oper2Impl();
    return oper2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Oper3 createOper3()
  {
    Oper3Impl oper3 = new Oper3Impl();
    return oper3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DATABASE createDATABASE()
  {
    DATABASEImpl database = new DATABASEImpl();
    return database;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CREATE createCREATE()
  {
    CREATEImpl create = new CREATEImpl();
    return create;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TABLE createTABLE()
  {
    TABLEImpl table = new TABLEImpl();
    return table;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TableName createTableName()
  {
    TableNameImpl tableName = new TableNameImpl();
    return tableName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CD createCD()
  {
    CDImpl cd = new CDImpl();
    return cd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrimaryKey createPrimaryKey()
  {
    PrimaryKeyImpl primaryKey = new PrimaryKeyImpl();
    return primaryKey;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ForeignKey createForeignKey()
  {
    ForeignKeyImpl foreignKey = new ForeignKeyImpl();
    return foreignKey;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DROPTABLE createDROPTABLE()
  {
    DROPTABLEImpl droptable = new DROPTABLEImpl();
    return droptable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TRUNCATE createTRUNCATE()
  {
    TRUNCATEImpl truncate = new TRUNCATEImpl();
    return truncate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DELETE createDELETE()
  {
    DELETEImpl delete = new DELETEImpl();
    return delete;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UPDATE createUPDATE()
  {
    UPDATEImpl update = new UPDATEImpl();
    return update;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SetClause createSetClause()
  {
    SetClauseImpl setClause = new SetClauseImpl();
    return setClause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ALTER createALTER()
  {
    ALTERImpl alter = new ALTERImpl();
    return alter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ALTERDROP createALTERDROP()
  {
    ALTERDROPImpl alterdrop = new ALTERDROPImpl();
    return alterdrop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ALTERADD createALTERADD()
  {
    ALTERADDImpl alteradd = new ALTERADDImpl();
    return alteradd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ALTERUPDATE createALTERUPDATE()
  {
    ALTERUPDATEImpl alterupdate = new ALTERUPDATEImpl();
    return alterupdate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableDeclaration createVariableDeclaration()
  {
    VariableDeclarationImpl variableDeclaration = new VariableDeclarationImpl();
    return variableDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntLiteral createIntLiteral()
  {
    IntLiteralImpl intLiteral = new IntLiteralImpl();
    return intLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RealLiteral createRealLiteral()
  {
    RealLiteralImpl realLiteral = new RealLiteralImpl();
    return realLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntVarExpression createIntVarExpression()
  {
    IntVarExpressionImpl intVarExpression = new IntVarExpressionImpl();
    return intVarExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SELECTFUNCT createSELECTFUNCT()
  {
    SELECTFUNCTImpl selectfunct = new SELECTFUNCTImpl();
    return selectfunct;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CountFunction createCountFunction()
  {
    CountFunctionImpl countFunction = new CountFunctionImpl();
    return countFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AvgFunction createAvgFunction()
  {
    AvgFunctionImpl avgFunction = new AvgFunctionImpl();
    return avgFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SumFunction createSumFunction()
  {
    SumFunctionImpl sumFunction = new SumFunctionImpl();
    return sumFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MinFunction createMinFunction()
  {
    MinFunctionImpl minFunction = new MinFunctionImpl();
    return minFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MaxFunction createMaxFunction()
  {
    MaxFunctionImpl maxFunction = new MaxFunctionImpl();
    return maxFunction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public INSERT createINSERT()
  {
    INSERTImpl insert = new INSERTImpl();
    return insert;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DATATYPE createDATATYPEFromString(EDataType eDataType, String initialValue)
  {
    DATATYPE result = DATATYPE.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertDATATYPEToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MyDslPackage getMyDslPackage()
  {
    return (MyDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static MyDslPackage getPackage()
  {
    return MyDslPackage.eINSTANCE;
  }

} //MyDslFactoryImpl
