/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl.impl;

import java.util.Collection;

import mydsl.myDsl.MyDslPackage;
import mydsl.myDsl.SetClause;
import mydsl.myDsl.TableName;
import mydsl.myDsl.UPDATE;
import mydsl.myDsl.WHERE;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>UPDATE</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.impl.UPDATEImpl#getTable <em>Table</em>}</li>
 *   <li>{@link mydsl.myDsl.impl.UPDATEImpl#getSc <em>Sc</em>}</li>
 *   <li>{@link mydsl.myDsl.impl.UPDATEImpl#getZ <em>Z</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UPDATEImpl extends ElementImpl implements UPDATE
{
  /**
   * The cached value of the '{@link #getTable() <em>Table</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTable()
   * @generated
   * @ordered
   */
  protected EList<TableName> table;

  /**
   * The cached value of the '{@link #getSc() <em>Sc</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSc()
   * @generated
   * @ordered
   */
  protected EList<SetClause> sc;

  /**
   * The cached value of the '{@link #getZ() <em>Z</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZ()
   * @generated
   * @ordered
   */
  protected EList<WHERE> z;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UPDATEImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.UPDATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<TableName> getTable()
  {
    if (table == null)
    {
      table = new EObjectResolvingEList<TableName>(TableName.class, this, MyDslPackage.UPDATE__TABLE);
    }
    return table;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<SetClause> getSc()
  {
    if (sc == null)
    {
      sc = new EObjectContainmentEList<SetClause>(SetClause.class, this, MyDslPackage.UPDATE__SC);
    }
    return sc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WHERE> getZ()
  {
    if (z == null)
    {
      z = new EObjectContainmentEList<WHERE>(WHERE.class, this, MyDslPackage.UPDATE__Z);
    }
    return z;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.UPDATE__SC:
        return ((InternalEList<?>)getSc()).basicRemove(otherEnd, msgs);
      case MyDslPackage.UPDATE__Z:
        return ((InternalEList<?>)getZ()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.UPDATE__TABLE:
        return getTable();
      case MyDslPackage.UPDATE__SC:
        return getSc();
      case MyDslPackage.UPDATE__Z:
        return getZ();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.UPDATE__TABLE:
        getTable().clear();
        getTable().addAll((Collection<? extends TableName>)newValue);
        return;
      case MyDslPackage.UPDATE__SC:
        getSc().clear();
        getSc().addAll((Collection<? extends SetClause>)newValue);
        return;
      case MyDslPackage.UPDATE__Z:
        getZ().clear();
        getZ().addAll((Collection<? extends WHERE>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.UPDATE__TABLE:
        getTable().clear();
        return;
      case MyDslPackage.UPDATE__SC:
        getSc().clear();
        return;
      case MyDslPackage.UPDATE__Z:
        getZ().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.UPDATE__TABLE:
        return table != null && !table.isEmpty();
      case MyDslPackage.UPDATE__SC:
        return sc != null && !sc.isEmpty();
      case MyDslPackage.UPDATE__Z:
        return z != null && !z.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //UPDATEImpl
