/*
 * generated by Xtext 2.23.0
 */
package mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import mydsl.services.MyDslGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
			builder.put(grammarAccess.getSELECTAccess().getAlternatives_1(), "rule__SELECT__Alternatives_1");
			builder.put(grammarAccess.getFromAndWhereClausesAccess().getAlternatives_2_2_0(), "rule__FromAndWhereClauses__Alternatives_2_2_0");
			builder.put(grammarAccess.getWHEREAccess().getSignAlternatives_1_0(), "rule__WHERE__SignAlternatives_1_0");
			builder.put(grammarAccess.getWHEREAccess().getOperAlternatives_2_0(), "rule__WHERE__OperAlternatives_2_0");
			builder.put(grammarAccess.getTABLEAccess().getAttributesAlternatives_4_0(), "rule__TABLE__AttributesAlternatives_4_0");
			builder.put(grammarAccess.getTABLEAccess().getAttributesAlternatives_5_1_0(), "rule__TABLE__AttributesAlternatives_5_1_0");
			builder.put(grammarAccess.getUPDATEAccess().getAlternatives_5_2_0(), "rule__UPDATE__Alternatives_5_2_0");
			builder.put(grammarAccess.getSetClauseAccess().getAlternatives_2(), "rule__SetClause__Alternatives_2");
			builder.put(grammarAccess.getALTERAccess().getAddDropUpdateAlternatives_3_0(), "rule__ALTER__AddDropUpdateAlternatives_3_0");
			builder.put(grammarAccess.getSELECTFUNCTAccess().getAlternatives(), "rule__SELECTFUNCT__Alternatives");
			builder.put(grammarAccess.getDATATYPEAccess().getAlternatives(), "rule__DATATYPE__Alternatives");
			builder.put(grammarAccess.getREALAccess().getGroup(), "rule__REAL__Group__0");
			builder.put(grammarAccess.getSELECTAccess().getGroup(), "rule__SELECT__Group__0");
			builder.put(grammarAccess.getSELECTAccess().getGroup_1_1(), "rule__SELECT__Group_1_1__0");
			builder.put(grammarAccess.getSELECTAccess().getGroup_1_1_1(), "rule__SELECT__Group_1_1_1__0");
			builder.put(grammarAccess.getFromAndWhereClausesAccess().getGroup(), "rule__FromAndWhereClauses__Group__0");
			builder.put(grammarAccess.getFromAndWhereClausesAccess().getGroup_2(), "rule__FromAndWhereClauses__Group_2__0");
			builder.put(grammarAccess.getFromAndWhereClausesAccess().getGroup_2_2(), "rule__FromAndWhereClauses__Group_2_2__0");
			builder.put(grammarAccess.getWHEREAccess().getGroup(), "rule__WHERE__Group__0");
			builder.put(grammarAccess.getOper1Access().getGroup(), "rule__Oper1__Group__0");
			builder.put(grammarAccess.getDATABASEAccess().getGroup(), "rule__DATABASE__Group__0");
			builder.put(grammarAccess.getTABLEAccess().getGroup(), "rule__TABLE__Group__0");
			builder.put(grammarAccess.getTABLEAccess().getGroup_5(), "rule__TABLE__Group_5__0");
			builder.put(grammarAccess.getColumnDeclarationAccess().getGroup(), "rule__ColumnDeclaration__Group__0");
			builder.put(grammarAccess.getPrimaryKeyAccess().getGroup(), "rule__PrimaryKey__Group__0");
			builder.put(grammarAccess.getPrimaryKeyAccess().getGroup_4(), "rule__PrimaryKey__Group_4__0");
			builder.put(grammarAccess.getForeignKeyAccess().getGroup(), "rule__ForeignKey__Group__0");
			builder.put(grammarAccess.getForeignKeyAccess().getGroup_4(), "rule__ForeignKey__Group_4__0");
			builder.put(grammarAccess.getForeignKeyAccess().getGroup_10(), "rule__ForeignKey__Group_10__0");
			builder.put(grammarAccess.getDROPTABLEAccess().getGroup(), "rule__DROPTABLE__Group__0");
			builder.put(grammarAccess.getDROPTABLEAccess().getGroup_3(), "rule__DROPTABLE__Group_3__0");
			builder.put(grammarAccess.getTRUNCATEAccess().getGroup(), "rule__TRUNCATE__Group__0");
			builder.put(grammarAccess.getTRUNCATEAccess().getGroup_3(), "rule__TRUNCATE__Group_3__0");
			builder.put(grammarAccess.getDELETEAccess().getGroup(), "rule__DELETE__Group__0");
			builder.put(grammarAccess.getUPDATEAccess().getGroup(), "rule__UPDATE__Group__0");
			builder.put(grammarAccess.getUPDATEAccess().getGroup_4(), "rule__UPDATE__Group_4__0");
			builder.put(grammarAccess.getUPDATEAccess().getGroup_5(), "rule__UPDATE__Group_5__0");
			builder.put(grammarAccess.getUPDATEAccess().getGroup_5_2(), "rule__UPDATE__Group_5_2__0");
			builder.put(grammarAccess.getSetClauseAccess().getGroup(), "rule__SetClause__Group__0");
			builder.put(grammarAccess.getSetClauseAccess().getGroup_2_0(), "rule__SetClause__Group_2_0__0");
			builder.put(grammarAccess.getALTERAccess().getGroup(), "rule__ALTER__Group__0");
			builder.put(grammarAccess.getALTERDROPAccess().getGroup(), "rule__ALTERDROP__Group__0");
			builder.put(grammarAccess.getALTERADDAccess().getGroup(), "rule__ALTERADD__Group__0");
			builder.put(grammarAccess.getALTERUPDATEAccess().getGroup(), "rule__ALTERUPDATE__Group__0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getGroup(), "rule__VariableDeclaration__Group__0");
			builder.put(grammarAccess.getCountFunctionAccess().getGroup(), "rule__CountFunction__Group__0");
			builder.put(grammarAccess.getAvgFunctionAccess().getGroup(), "rule__AvgFunction__Group__0");
			builder.put(grammarAccess.getSumFunctionAccess().getGroup(), "rule__SumFunction__Group__0");
			builder.put(grammarAccess.getMinFunctionAccess().getGroup(), "rule__MinFunction__Group__0");
			builder.put(grammarAccess.getMaxFunctionAccess().getGroup(), "rule__MaxFunction__Group__0");
			builder.put(grammarAccess.getINSERTAccess().getGroup(), "rule__INSERT__Group__0");
			builder.put(grammarAccess.getModelAccess().getElementAssignment(), "rule__Model__ElementAssignment");
			builder.put(grammarAccess.getSELECTAccess().getColumnAssignment_1_1_0(), "rule__SELECT__ColumnAssignment_1_1_0");
			builder.put(grammarAccess.getSELECTAccess().getColumnAssignment_1_1_1_1(), "rule__SELECT__ColumnAssignment_1_1_1_1");
			builder.put(grammarAccess.getSELECTAccess().getXAssignment_2(), "rule__SELECT__XAssignment_2");
			builder.put(grammarAccess.getFromAndWhereClausesAccess().getTableAssignment_1(), "rule__FromAndWhereClauses__TableAssignment_1");
			builder.put(grammarAccess.getFromAndWhereClausesAccess().getZAssignment_2_1(), "rule__FromAndWhereClauses__ZAssignment_2_1");
			builder.put(grammarAccess.getFromAndWhereClausesAccess().getZAssignment_2_2_1(), "rule__FromAndWhereClauses__ZAssignment_2_2_1");
			builder.put(grammarAccess.getWHEREAccess().getColumnAssignment_0(), "rule__WHERE__ColumnAssignment_0");
			builder.put(grammarAccess.getWHEREAccess().getSignAssignment_1(), "rule__WHERE__SignAssignment_1");
			builder.put(grammarAccess.getWHEREAccess().getOperAssignment_2(), "rule__WHERE__OperAssignment_2");
			builder.put(grammarAccess.getOper1Access().getNameAssignment_1(), "rule__Oper1__NameAssignment_1");
			builder.put(grammarAccess.getOper2Access().getColumnAssignment(), "rule__Oper2__ColumnAssignment");
			builder.put(grammarAccess.getOper3Access().getValAssignment(), "rule__Oper3__ValAssignment");
			builder.put(grammarAccess.getDATABASEAccess().getNameAssignment_2(), "rule__DATABASE__NameAssignment_2");
			builder.put(grammarAccess.getCREATEAccess().getTablesAssignment(), "rule__CREATE__TablesAssignment");
			builder.put(grammarAccess.getTABLEAccess().getTableAssignment_2(), "rule__TABLE__TableAssignment_2");
			builder.put(grammarAccess.getTABLEAccess().getAttributesAssignment_4(), "rule__TABLE__AttributesAssignment_4");
			builder.put(grammarAccess.getTABLEAccess().getAttributesAssignment_5_1(), "rule__TABLE__AttributesAssignment_5_1");
			builder.put(grammarAccess.getTableNameAccess().getNameAssignment(), "rule__TableName__NameAssignment");
			builder.put(grammarAccess.getColumnDeclarationAccess().getNameAssignment_0(), "rule__ColumnDeclaration__NameAssignment_0");
			builder.put(grammarAccess.getColumnDeclarationAccess().getTypeAssignment_1(), "rule__ColumnDeclaration__TypeAssignment_1");
			builder.put(grammarAccess.getColumnDeclarationAccess().getNotNullAssignment_2(), "rule__ColumnDeclaration__NotNullAssignment_2");
			builder.put(grammarAccess.getPrimaryKeyAccess().getColumnAsPKAssignment_3(), "rule__PrimaryKey__ColumnAsPKAssignment_3");
			builder.put(grammarAccess.getPrimaryKeyAccess().getColumnAsPKAssignment_4_1(), "rule__PrimaryKey__ColumnAsPKAssignment_4_1");
			builder.put(grammarAccess.getForeignKeyAccess().getColumnAsFKAssignment_3(), "rule__ForeignKey__ColumnAsFKAssignment_3");
			builder.put(grammarAccess.getForeignKeyAccess().getColumnAsFKAssignment_4_1(), "rule__ForeignKey__ColumnAsFKAssignment_4_1");
			builder.put(grammarAccess.getForeignKeyAccess().getForeignTableAssignment_7(), "rule__ForeignKey__ForeignTableAssignment_7");
			builder.put(grammarAccess.getForeignKeyAccess().getForeignColumnsAssignment_9(), "rule__ForeignKey__ForeignColumnsAssignment_9");
			builder.put(grammarAccess.getForeignKeyAccess().getForeignColumnsAssignment_10_1(), "rule__ForeignKey__ForeignColumnsAssignment_10_1");
			builder.put(grammarAccess.getDROPTABLEAccess().getTableAssignment_2(), "rule__DROPTABLE__TableAssignment_2");
			builder.put(grammarAccess.getDROPTABLEAccess().getTableAssignment_3_1(), "rule__DROPTABLE__TableAssignment_3_1");
			builder.put(grammarAccess.getTRUNCATEAccess().getTableAssignment_2(), "rule__TRUNCATE__TableAssignment_2");
			builder.put(grammarAccess.getTRUNCATEAccess().getTableAssignment_3_1(), "rule__TRUNCATE__TableAssignment_3_1");
			builder.put(grammarAccess.getDELETEAccess().getXAssignment_1(), "rule__DELETE__XAssignment_1");
			builder.put(grammarAccess.getUPDATEAccess().getTableAssignment_1(), "rule__UPDATE__TableAssignment_1");
			builder.put(grammarAccess.getUPDATEAccess().getScAssignment_3(), "rule__UPDATE__ScAssignment_3");
			builder.put(grammarAccess.getUPDATEAccess().getScAssignment_4_1(), "rule__UPDATE__ScAssignment_4_1");
			builder.put(grammarAccess.getUPDATEAccess().getZAssignment_5_1(), "rule__UPDATE__ZAssignment_5_1");
			builder.put(grammarAccess.getUPDATEAccess().getZAssignment_5_2_1(), "rule__UPDATE__ZAssignment_5_2_1");
			builder.put(grammarAccess.getSetClauseAccess().getColumnAssignment_0(), "rule__SetClause__ColumnAssignment_0");
			builder.put(grammarAccess.getSetClauseAccess().getNameAssignment_2_0_1(), "rule__SetClause__NameAssignment_2_0_1");
			builder.put(grammarAccess.getSetClauseAccess().getValAssignment_2_1(), "rule__SetClause__ValAssignment_2_1");
			builder.put(grammarAccess.getALTERAccess().getTableAssignment_2(), "rule__ALTER__TableAssignment_2");
			builder.put(grammarAccess.getALTERAccess().getAddDropUpdateAssignment_3(), "rule__ALTER__AddDropUpdateAssignment_3");
			builder.put(grammarAccess.getALTERDROPAccess().getColumnAssignment_2(), "rule__ALTERDROP__ColumnAssignment_2");
			builder.put(grammarAccess.getALTERADDAccess().getColumnAssignment_1(), "rule__ALTERADD__ColumnAssignment_1");
			builder.put(grammarAccess.getALTERUPDATEAccess().getColumnAssignment_2(), "rule__ALTERUPDATE__ColumnAssignment_2");
			builder.put(grammarAccess.getVariableDeclarationAccess().getNameAssignment_1(), "rule__VariableDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getVariableDeclarationAccess().getValueAssignment_3(), "rule__VariableDeclaration__ValueAssignment_3");
			builder.put(grammarAccess.getIntLiteralAccess().getValAssignment(), "rule__IntLiteral__ValAssignment");
			builder.put(grammarAccess.getRealLiteralAccess().getValAssignment(), "rule__RealLiteral__ValAssignment");
			builder.put(grammarAccess.getIntVarExpressionAccess().getVarAssignment(), "rule__IntVarExpression__VarAssignment");
			builder.put(grammarAccess.getCountFunctionAccess().getColumnAssignment_3(), "rule__CountFunction__ColumnAssignment_3");
			builder.put(grammarAccess.getCountFunctionAccess().getXAssignment_5(), "rule__CountFunction__XAssignment_5");
			builder.put(grammarAccess.getAvgFunctionAccess().getColumnAssignment_3(), "rule__AvgFunction__ColumnAssignment_3");
			builder.put(grammarAccess.getAvgFunctionAccess().getXAssignment_5(), "rule__AvgFunction__XAssignment_5");
			builder.put(grammarAccess.getSumFunctionAccess().getColumnAssignment_3(), "rule__SumFunction__ColumnAssignment_3");
			builder.put(grammarAccess.getSumFunctionAccess().getXAssignment_5(), "rule__SumFunction__XAssignment_5");
			builder.put(grammarAccess.getMinFunctionAccess().getColumnAssignment_3(), "rule__MinFunction__ColumnAssignment_3");
			builder.put(grammarAccess.getMinFunctionAccess().getXAssignment_5(), "rule__MinFunction__XAssignment_5");
			builder.put(grammarAccess.getMaxFunctionAccess().getColumnAssignment_3(), "rule__MaxFunction__ColumnAssignment_3");
			builder.put(grammarAccess.getMaxFunctionAccess().getXAssignment_5(), "rule__MaxFunction__XAssignment_5");
			builder.put(grammarAccess.getINSERTAccess().getNameTAssignment_2(), "rule__INSERT__NameTAssignment_2");
			builder.put(grammarAccess.getINSERTAccess().getLiteralsAssignment_5(), "rule__INSERT__LiteralsAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
