/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ALTER</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.ALTER#getTable <em>Table</em>}</li>
 *   <li>{@link mydsl.myDsl.ALTER#getAddDropUpdate <em>Add Drop Update</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getALTER()
 * @model
 * @generated
 */
public interface ALTER extends Element
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference list.
   * The list contents are of type {@link mydsl.myDsl.TableName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference list.
   * @see mydsl.myDsl.MyDslPackage#getALTER_Table()
   * @model
   * @generated
   */
  EList<TableName> getTable();

  /**
   * Returns the value of the '<em><b>Add Drop Update</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Add Drop Update</em>' containment reference.
   * @see #setAddDropUpdate(EObject)
   * @see mydsl.myDsl.MyDslPackage#getALTER_AddDropUpdate()
   * @model containment="true"
   * @generated
   */
  EObject getAddDropUpdate();

  /**
   * Sets the value of the '{@link mydsl.myDsl.ALTER#getAddDropUpdate <em>Add Drop Update</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Add Drop Update</em>' containment reference.
   * @see #getAddDropUpdate()
   * @generated
   */
  void setAddDropUpdate(EObject value);

} // ALTER
