/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Avg Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mydsl.myDsl.MyDslPackage#getAvgFunction()
 * @model
 * @generated
 */
public interface AvgFunction extends SELECTFUNCT
{
} // AvgFunction
