/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CREATE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.CREATE#getTables <em>Tables</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getCREATE()
 * @model
 * @generated
 */
public interface CREATE extends Element
{
  /**
   * Returns the value of the '<em><b>Tables</b></em>' containment reference list.
   * The list contents are of type {@link mydsl.myDsl.TABLE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tables</em>' containment reference list.
   * @see mydsl.myDsl.MyDslPackage#getCREATE_Tables()
   * @model containment="true"
   * @generated
   */
  EList<TABLE> getTables();

} // CREATE
