/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DATABASE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.DATABASE#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getDATABASE()
 * @model
 * @generated
 */
public interface DATABASE extends Element
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mydsl.myDsl.MyDslPackage#getDATABASE_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mydsl.myDsl.DATABASE#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // DATABASE
