/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DELETE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.DELETE#getX <em>X</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getDELETE()
 * @model
 * @generated
 */
public interface DELETE extends Element
{
  /**
   * Returns the value of the '<em><b>X</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' containment reference.
   * @see #setX(FromAndWhereClauses)
   * @see mydsl.myDsl.MyDslPackage#getDELETE_X()
   * @model containment="true"
   * @generated
   */
  FromAndWhereClauses getX();

  /**
   * Sets the value of the '{@link mydsl.myDsl.DELETE#getX <em>X</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' containment reference.
   * @see #getX()
   * @generated
   */
  void setX(FromAndWhereClauses value);

} // DELETE
