/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DROPTABLE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.DROPTABLE#getTable <em>Table</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getDROPTABLE()
 * @model
 * @generated
 */
public interface DROPTABLE extends Element
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference list.
   * The list contents are of type {@link mydsl.myDsl.TableName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference list.
   * @see mydsl.myDsl.MyDslPackage#getDROPTABLE_Table()
   * @model
   * @generated
   */
  EList<TableName> getTable();

} // DROPTABLE
