/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Foreign Key</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.ForeignKey#getColumnAsFK <em>Column As FK</em>}</li>
 *   <li>{@link mydsl.myDsl.ForeignKey#getForeignTable <em>Foreign Table</em>}</li>
 *   <li>{@link mydsl.myDsl.ForeignKey#getForeignColumns <em>Foreign Columns</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getForeignKey()
 * @model
 * @generated
 */
public interface ForeignKey extends EObject
{
  /**
   * Returns the value of the '<em><b>Column As FK</b></em>' reference list.
   * The list contents are of type {@link mydsl.myDsl.CD}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column As FK</em>' reference list.
   * @see mydsl.myDsl.MyDslPackage#getForeignKey_ColumnAsFK()
   * @model
   * @generated
   */
  EList<CD> getColumnAsFK();

  /**
   * Returns the value of the '<em><b>Foreign Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foreign Table</em>' reference.
   * @see #setForeignTable(TABLE)
   * @see mydsl.myDsl.MyDslPackage#getForeignKey_ForeignTable()
   * @model
   * @generated
   */
  TABLE getForeignTable();

  /**
   * Sets the value of the '{@link mydsl.myDsl.ForeignKey#getForeignTable <em>Foreign Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Foreign Table</em>' reference.
   * @see #getForeignTable()
   * @generated
   */
  void setForeignTable(TABLE value);

  /**
   * Returns the value of the '<em><b>Foreign Columns</b></em>' reference list.
   * The list contents are of type {@link mydsl.myDsl.CD}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foreign Columns</em>' reference list.
   * @see mydsl.myDsl.MyDslPackage#getForeignKey_ForeignColumns()
   * @model
   * @generated
   */
  EList<CD> getForeignColumns();

} // ForeignKey
