/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>From And Where Clauses</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.FromAndWhereClauses#getTable <em>Table</em>}</li>
 *   <li>{@link mydsl.myDsl.FromAndWhereClauses#getZ <em>Z</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getFromAndWhereClauses()
 * @model
 * @generated
 */
public interface FromAndWhereClauses extends EObject
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference.
   * @see #setTable(TableName)
   * @see mydsl.myDsl.MyDslPackage#getFromAndWhereClauses_Table()
   * @model
   * @generated
   */
  TableName getTable();

  /**
   * Sets the value of the '{@link mydsl.myDsl.FromAndWhereClauses#getTable <em>Table</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' reference.
   * @see #getTable()
   * @generated
   */
  void setTable(TableName value);

  /**
   * Returns the value of the '<em><b>Z</b></em>' containment reference list.
   * The list contents are of type {@link mydsl.myDsl.WHERE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Z</em>' containment reference list.
   * @see mydsl.myDsl.MyDslPackage#getFromAndWhereClauses_Z()
   * @model containment="true"
   * @generated
   */
  EList<WHERE> getZ();

} // FromAndWhereClauses
