/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>INSERT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.INSERT#getNameT <em>Name T</em>}</li>
 *   <li>{@link mydsl.myDsl.INSERT#getLiterals <em>Literals</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getINSERT()
 * @model
 * @generated
 */
public interface INSERT extends Element
{
  /**
   * Returns the value of the '<em><b>Name T</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name T</em>' attribute.
   * @see #setNameT(String)
   * @see mydsl.myDsl.MyDslPackage#getINSERT_NameT()
   * @model
   * @generated
   */
  String getNameT();

  /**
   * Sets the value of the '{@link mydsl.myDsl.INSERT#getNameT <em>Name T</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name T</em>' attribute.
   * @see #getNameT()
   * @generated
   */
  void setNameT(String value);

  /**
   * Returns the value of the '<em><b>Literals</b></em>' attribute list.
   * The list contents are of type {@link mydsl.myDsl.DATATYPE}.
   * The literals are from the enumeration {@link mydsl.myDsl.DATATYPE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literals</em>' attribute list.
   * @see mydsl.myDsl.DATATYPE
   * @see mydsl.myDsl.MyDslPackage#getINSERT_Literals()
   * @model unique="false"
   * @generated
   */
  EList<DATATYPE> getLiterals();

} // INSERT
