/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Min Function</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mydsl.myDsl.MyDslPackage#getMinFunction()
 * @model
 * @generated
 */
public interface MinFunction extends SELECTFUNCT
{
} // MinFunction
