/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Oper3</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.Oper3#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getOper3()
 * @model
 * @generated
 */
public interface Oper3 extends EObject
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(int)
   * @see mydsl.myDsl.MyDslPackage#getOper3_Val()
   * @model
   * @generated
   */
  int getVal();

  /**
   * Sets the value of the '{@link mydsl.myDsl.Oper3#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(int value);

} // Oper3
