/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Primary Key</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.PrimaryKey#getColumnAsPK <em>Column As PK</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getPrimaryKey()
 * @model
 * @generated
 */
public interface PrimaryKey extends EObject
{
  /**
   * Returns the value of the '<em><b>Column As PK</b></em>' reference list.
   * The list contents are of type {@link mydsl.myDsl.CD}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column As PK</em>' reference list.
   * @see mydsl.myDsl.MyDslPackage#getPrimaryKey_ColumnAsPK()
   * @model
   * @generated
   */
  EList<CD> getColumnAsPK();

} // PrimaryKey
