/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.RealLiteral#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getRealLiteral()
 * @model
 * @generated
 */
public interface RealLiteral extends EObject
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(float)
   * @see mydsl.myDsl.MyDslPackage#getRealLiteral_Val()
   * @model
   * @generated
   */
  float getVal();

  /**
   * Sets the value of the '{@link mydsl.myDsl.RealLiteral#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(float value);

} // RealLiteral
