/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TABLE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.TABLE#getTable <em>Table</em>}</li>
 *   <li>{@link mydsl.myDsl.TABLE#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getTABLE()
 * @model
 * @generated
 */
public interface TABLE extends EObject
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' containment reference list.
   * The list contents are of type {@link mydsl.myDsl.TableName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' containment reference list.
   * @see mydsl.myDsl.MyDslPackage#getTABLE_Table()
   * @model containment="true"
   * @generated
   */
  EList<TableName> getTable();

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see mydsl.myDsl.MyDslPackage#getTABLE_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getAttributes();

} // TABLE
