/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UPDATE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.UPDATE#getTable <em>Table</em>}</li>
 *   <li>{@link mydsl.myDsl.UPDATE#getSc <em>Sc</em>}</li>
 *   <li>{@link mydsl.myDsl.UPDATE#getZ <em>Z</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getUPDATE()
 * @model
 * @generated
 */
public interface UPDATE extends Element
{
  /**
   * Returns the value of the '<em><b>Table</b></em>' reference list.
   * The list contents are of type {@link mydsl.myDsl.TableName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' reference list.
   * @see mydsl.myDsl.MyDslPackage#getUPDATE_Table()
   * @model
   * @generated
   */
  EList<TableName> getTable();

  /**
   * Returns the value of the '<em><b>Sc</b></em>' containment reference list.
   * The list contents are of type {@link mydsl.myDsl.SetClause}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sc</em>' containment reference list.
   * @see mydsl.myDsl.MyDslPackage#getUPDATE_Sc()
   * @model containment="true"
   * @generated
   */
  EList<SetClause> getSc();

  /**
   * Returns the value of the '<em><b>Z</b></em>' containment reference list.
   * The list contents are of type {@link mydsl.myDsl.WHERE}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Z</em>' containment reference list.
   * @see mydsl.myDsl.MyDslPackage#getUPDATE_Z()
   * @model containment="true"
   * @generated
   */
  EList<WHERE> getZ();

} // UPDATE
