/**
 * generated by Xtext 2.23.0
 */
package mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>WHERE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mydsl.myDsl.WHERE#getColumn <em>Column</em>}</li>
 *   <li>{@link mydsl.myDsl.WHERE#getSign <em>Sign</em>}</li>
 *   <li>{@link mydsl.myDsl.WHERE#getOper <em>Oper</em>}</li>
 * </ul>
 *
 * @see mydsl.myDsl.MyDslPackage#getWHERE()
 * @model
 * @generated
 */
public interface WHERE extends EObject
{
  /**
   * Returns the value of the '<em><b>Column</b></em>' reference list.
   * The list contents are of type {@link mydsl.myDsl.CD}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' reference list.
   * @see mydsl.myDsl.MyDslPackage#getWHERE_Column()
   * @model
   * @generated
   */
  EList<CD> getColumn();

  /**
   * Returns the value of the '<em><b>Sign</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sign</em>' attribute.
   * @see #setSign(String)
   * @see mydsl.myDsl.MyDslPackage#getWHERE_Sign()
   * @model
   * @generated
   */
  String getSign();

  /**
   * Sets the value of the '{@link mydsl.myDsl.WHERE#getSign <em>Sign</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sign</em>' attribute.
   * @see #getSign()
   * @generated
   */
  void setSign(String value);

  /**
   * Returns the value of the '<em><b>Oper</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Oper</em>' containment reference.
   * @see #setOper(EObject)
   * @see mydsl.myDsl.MyDslPackage#getWHERE_Oper()
   * @model containment="true"
   * @generated
   */
  EObject getOper();

  /**
   * Sets the value of the '{@link mydsl.myDsl.WHERE#getOper <em>Oper</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Oper</em>' containment reference.
   * @see #getOper()
   * @generated
   */
  void setOper(EObject value);

} // WHERE
