/*
 * generated by Xtext 2.23.0
 */
package mydsl.ui.tests;

import com.google.inject.Injector;
import mydsl.ui.internal.MydslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("mydsl.MyDsl");
	}

}
